### ISSUE TITLE
Demon Ship -- add damaged ship model

### ISSUE THREAD

**Issue by FrogBucket** [MoreEventsMod/More_Events_Mod_Beta#101]
Science ship mesh ID's:
arthropoid_01_science.mesh                  lowpolyUnExploded:MeshShape
avian_01_science.mesh                         lowpoly:polySurface51Shape
fungoid_01_science.mesh                      pasted_polySurface188Shape
mammalian_01_science.mesh                rigg:MeshShape
molluscoid_01_science.mesh                 science_MeshShape
reptilian_01_science.mesh                     science_MeshShape

**Comment by Elimdur** [comment]
This means adding an ambient object looking like a science ship of your ship style with a damaged texture. So codewise you have to check which style your species uses to then take the according ambient object from the pool (Those objects have to be created first aswell, or did somebody already do this?).
