### ISSUE TITLE
Viral Engine needs testing

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#102]
The viral engine event needs testing. Check out the `dev` or `viral-engine` branch and run `event mem_viral_engine.9` to test.

**Comment by Tuttu** [comment]
Le 6 juil. 2016 3:19 AM, "Tim Carrell" <notifications@github.com> a écrit :

>

> The viral engine event needs testing. Check out the dev our viral-engine
branch and run event mem_viral_engine to test.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
<https://github.com/MoreEventsMod/More_Events_Mod_Beta/issues/102>, or mute
the thread
<https://github.com/notifications/unsubscribe/AA81vTCFIgyTUeWcGfRvK1ekEMBlGCziks5qSwKRgaJpZM4JFrCr>
.

**Comment by Deytron** [comment]
Just so you know, I just tried to run the event `mem_viral_engine.9` and here is what I get : 

![capture](https://cloud.githubusercontent.com/assets/20344764/16775624/d0766fbc-4861-11e6-86d7-3dab5e1d9a43.PNG)

I don't know if this is intended or if I'm doing something wrong.

**Comment by tzerrell** [comment]
Thanks for testing! If you are playing in a localisation other than English, this is correct (because it hasn't been translated yet, and this isn't a release so we haven't copied English into untranslated files). If you are playing in English, this means there's a problem with how I connected the loc file.

P.S.: The fact that it says "10" rather than "9" is fine. 9 is a hidden event that does setup and (sometimes) spawns 10.

**Comment by Deytron** [comment]
I'm playing in French, and I figured out that I haven't created a `mem_viral_engine_l_french.yml` file. If what you needed to know is "Does the event triggers properly ?", then the answer is yes.
But if you need the popup with the text, I can quickly do that. I think I may even take the time to translate this file into French because I have A LOT of free time. Just tell me.

**Comment by Deytron** [comment]
Confirmed working.

**Comment by tzerrell** [comment]
(now addressed)
