### ISSUE TITLE
Idea: Out of Limbo

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#126]
_idea by Noggy_
There's a survey event called "In Limbo" in vanilla, where you can download neural images of an extinct species. As far as I know, this is never brought up again. I expected you'd be able to download their memories to robots once your AI technology is advanced enough? Perhaps you can add an event where you can do that if you have done the survey and later unlock synths

**Comment by abif0** [comment]
This is in vanilla. You can either upload them into Synthetics once the tech is researched, and you can hand them off (in total or a copy) to the Xenophile FE.
