### ISSUE TITLE
Test Refactor

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#134]
We should really test the entire refactor; this means running every event and making sure nothing goes wrong. Here is what needs to be tested, and how to test it (the instructions for each are how to start the event; please test each event to completion):

_[Once you've tested an event to completion, please leave a comment here saying you've done so. Issues checked off have been tested, but could still benefit from more testing]_
- [x] Enterprise of the Fallen -- run `add_anomaly mem_enterprise_fallen_category` with an uninhabited planet selected, then survey
- [x] Mysterious Pyramids -- run `add_anomaly mem_mysterious_pyramids_category` with an uninhabitable planet selected, then survey
- [x] Poisoned World -- run `add_anomaly mem_poisoned_world_category` with an uninhabitable planet selected, then survey
- [x] Asteroid Structure Network - run `add_anomaly mem_asteroid_structure_category` with an asteroid selected, then survey
- [x] Crashed Object - run `add_anomaly mem_crashed_object_category` with an asteroid selected, then survey.
- [x] Elusive Carcosa - you need an empire with at least 5 planets. Run `event mem_elusive_carcosa.10`.
- [x] Dimensional Rift - run `add_anomaly mem_dimensional_rift_category` with a planet selected, then survey.
- [x] Demon Ship - run `add_anomaly mem_demon_ship_category` with a planet selected, then survey.
- [x] Dead Star - run `add_anomaly mem_dead_star_category` with a star selected, then survey.
- [x] Black Hole - run `add_anomaly mem_black_hole_1_category` with a star selected, then survey.
- [x] Lost Zoo - run `add_anomaly life_barren_category` with an uninhabited planet selected, then survey. Repeat until you get the lost zoo event -- this can also give you vanilla events.
- [x] Star Survey - run `event mem_star_survey.1`
- [x] Spiritualist Pilgrimage - run `event mem_spiritualists_pilgrimage.2` while you have spiritualist neighbors
- [x] Science Convention - run `event mem_science_convention.1` with at least one neighbor (preferably more)
- [x] Music Tour - run `event mem_music_tour.8` with at least one individualist neighbor
- [x] Imperialist Intimidation - run `event mem_imperialist_intimidation.7` with at least one hegemonic imperialists neighbor
- [x] Eager Traders 1 - run `event mem_eager_traders.1` with at least one Ruthless Capitalists neighbor
- [x] Eager Traders 2 - run `event mem_eager_traders.1` with at least one Peaceful Traders neighbor

**Comment by Lukasmar** [comment]
Tested: 
- Enterprise of the Fallen; tested to completion 
- Mysterious Pyramids; tested to completion  
- Poisoned World; tested to completion 
- Star Survey; tested to completion 
- Demon Ship; tested to completion  

Polish translation works

**Comment by Deytron** [comment]
Events that I've currently tested : 
- Asteroid Structure Network; tested to completion
- Crashed Object; tested to completion
- Elusive Carcosa; 60% completed
- Music Tour; tested to completion
- Eager Traders 1; tested to completion
- Eager Traders 2; confirmed working fine by Malthus
- Lost Zoo; tested to completion
- Spiritualist Pilgrimage; 20% tested. I have to try another route.

**Comment by Lukasmar** [comment]
Tested:
- Dimensional Rift;  tested to completion
- Dead Star; tested to completion
- Black Hole; tested to completion

**Comment by ghost** [comment]
Tested:

Science Convention:
1. It doesn't appear in the event log. I don't know if it should, but it would be nice to see the time till the convention and who accepted our invitation.
2. A neighbor who is in my federation (+230 opinion) declined the offer. Maybe it is random, maybe it isn't.
3. Some grammar issues I will fix and upload here.

Imperialist Intimidation:
1. After the event, it should be wise to add a pop-up window to see what option did we get.

Elusive Carcosa:
1. All good!

**Comment by tzerrell** [comment]
@SonofKrypton if the commit of yours I cherry-picked as f1ce0818 did not fix all the grammar issues you found, let me know so I can mark it as an unfinished issue.

Other than that, we have now tested everything, and all the resulting issues have been either fixed or added to the tracker. Good job testers, I'm closing this issue!

**Comment by ghost** [comment]
It's all good for that event. :)
