### ISSUE TITLE
Add mem_opinion_trustworthy to loc files

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#137]
As part of the elusive-carcosa event, mem_opinion_trustworthy should be in the loc files. It isn't

**Comment by tzerrell** [comment]
This is fixed in English in the most recent dev, but any translations of Elusive Carcosa will need to be redone.

**Comment by Deytron** [comment]
Now added to French localisation

**Comment by Elimdur** [comment]
added the translated entry into the german loc file
