### ISSUE TITLE
Bug in some events affecting species ?

### ISSUE THREAD

**Issue by Tuttu** [MoreEventsMod/More_Events_Mod_Beta#138]
[It might be a bug only limited to the steam version, but I'll report it anyways. If you have too much species diversity in your empire (like, 25+) events that account for every species seem to crash the same. ](http://forum.paradoxplaza.com/forum/index.php?threads/mod-more-events-mod-new-beta-available.945016/page-4#post-21586873)
We might want to investigate this and add some guardrails to prevent that.

**Comment by tzerrell** [comment]
I'm guessing this was addressed by the `every_owned_pop` fix (commit 9255d1ea), but if not we can reopen this.
