### ISSUE TITLE
Smaller anomalies and observation post flavor events.

### ISSUE THREAD

**Issue by Mariawr** [MoreEventsMod/More_Events_Mod_Beta#150]
I'm gonna start keeping a list of smaller anomaly ideas and just write and edit them as they come . Whenever a coder picks up an anomaly please tick one of the boxes, same with testing and implementation.
- [x] A disguised tundra world
  - [x] Coded
  - [x] Tested
  - [x] Ready to release
  - [x] Implemented in stable
- [x] They think we are gods ! (Implemented)

**Comment by Mariawr** [comment]
A tundra world disguises as barren rock: https://docs.google.com/document/d/1HLz1WK8kSsXclkyyk2cf-OAOtAsB9vWAcva0uAb1pSw/edit

**Comment by Mariawr** [comment]
Active research on natives yields in the result of them thinking us as gods: https://docs.google.com/document/d/1OAOYAF5QY_hYK5-E5cSplFJMAbV21TVi89nYW9VkROk/edit

**Comment by ghost** [comment]
There's an event in the existing game that might overlap with the "research on natives lead them to think we are gods" event.   It's not the same, but they are similar.

**Comment by Mariawr** [comment]
Yeah only found that one ages after the ours was done. It doesn't matter too much, ours is more flavor than anything.

**Comment by tzerrell** [comment]
I added the unreleased label for the tundra event; the We Are Gods one is good to go and that half of this issue can be considered closed.

**Comment by tzerrell** [comment]
I think the hidden tundra anomaly just needs testing before release. Test with `add_anomaly mem_hidden_tundra_category`. Removing current assignees as they are not the test team.

**Comment by tzerrell** [comment]
The hidden tundra anomaly has been tested and is in `stable`

**Comment by tzerrell** [comment]
It seems these are all complete, so I'm closing this. Feel free to reopen if I'm missing something.

**Comment by Mariawr** [comment]
This was meant to be a long-term thing, but kinda got lost when I dropped out for a while, I'll make a new one once I am working on things again.
