### ISSUE TITLE
How to make precursor chains finishable / Expanded precursor chains

### ISSUE THREAD

**Issue by Mariawr** [MoreEventsMod/More_Events_Mod_Beta#152]
Right now the precursor chains are pretty hard to complete in a standard setting while also giving really bad rewards. There is lots of space for improvement and ideas there.

**Comment by Elimdur** [comment]
First of all we should find a way to make those precursor event chains finishable at all.

The biggest problem is the availability of enough anomalies to finally get all projects (you need 6 of them). Usually I end up with 5 and never get the last one.

So we should find an easy and immersive way of dealing with thi.

My suggestion is:
1. Wait until a specific point in the game. I am just throwing in 40 years or so.
2. When this time is over check if one of the precursor chains is active.
3. If one is active and there are still artefacts to recover AND you lack according projects an event message should pop up telling you there has been an archeological finding somewhere in your empire ( can be generic).
4. When clicking on the "ok" button you get one of the according missing projects for your event chain somewhere inside your borders.
5. Wait some time then repeat the procedure until you don´t have the precursor event chain active anymore.

bam this way you will eventually get all the artefacts and can finish the precursor quest.

**Comment by tzerrell** [comment]
I like this and I suspect it would work. Maybe only 90% sure without actually coding it.

Also, we might consider doing it with a mean time to happen reduced by having more planets -- the more planets, the greater a chance any given one has something useful.

**Comment by Elimdur** [comment]
Sounds good to me. Once we have this working we can think about events that can happen after the end of the precursor quest. If you barely finish that quests at all it makes no sense for us to make events based on these ends ;)

But now that we have a plan. Maria could come forward with some of here cool ideas :)

**Comment by Mariawr** [comment]
To be honest, we probably only need a small pop-up message for that one and then just forward the player to the already existing precursor events so the stuff we need to write on the non-coding end is probably minimal with that method.

**Comment by tzerrell** [comment]
I coded up a a prototype event for this, to replace vultaum_1 if it has not spawned for the player as an anomaly. It appears to work perfectly, and I am confident that this approach will work for all the necessary precursor events.

The coding is actually rather straightforward, but a bit tedious. Given my time constraints due to the wedding, I'm going to see if another coder wants to take this up.

**Comment by Elimdur** [comment]
Have finished the copy paste job. Now it needs testing.

**Comment by Deytron** [comment]
Tested, confirmed working.
