### ISSUE TITLE
Game Freeze in Eager Traders Event

### ISSUE THREAD

**Issue by Elimdur** [MoreEventsMod/More_Events_Mod_Beta#158]
Dragonmalte  (steamworkshop forum)

> Game starts now with german language, but loading my save (82 years into the game without the mod) and advancing a few days I get 2 events first "Eifrige Unternehmer an unserer grenze" and second "Erste Händler kommen an." When Hovering over the choices for the second event (first traders) the game does not respond and i have to shut it down forcefully (i get the option for xenophiles import some delicacies and interessting for neutral). As I said when hovering over that option the game just freezes and windows tells me the program does not respond and does not work anymore and my only option is to shut it down forcefully.
> Playing with Beta 1.2.2 and all other mods are disabled.
> The error log shows:
> [23:40:13][modifier.cpp:334]: Missing modifier scripted icon gfx/interface/icons/planet_modifiers/mem_pm_graph_up.dds
> [23:40:13][modifier.cpp:334]: Missing modifier scripted icon gfx/interface/icons/planet_modifiers/mem_pm_graph_down.dds
> This happens with english language setting too, so its not a problem with the german localisation as far as i can see
> English name for the event that crashes is "First (empire name) traders arive" and the option that crashes is the xenophile option "great, some delicacies for me"
> Just hovering over the option causes the freeze, can't even click on it.
> EDIT: Loading another older game 150 years into the game i get the same 2 events but since i am not a xenophile in that game i do just get interesting as an option and that works without a freeze. Error log still shows the two missing modifiers even when the game does not freeze so they may not be related to the freeze.
> EDIT2: looked into the eager trader events file in the mod folder and it may be important to note that the empire that triggered the event was a peacefull trader so I think its the event with id = mem_eager_traders.5 and the option mem_eager_traders.5.xenophile that freezes.
> EDIT3: edited my save file to be xenophobe and individualistic to see if those options work. Hovering over the individualist option does NOT freeze but hovering over the option for Xenophobes freezes the game too. 
> For the trader event with rutheless capitalists all three options work (game does not freeze when hovering over them)
> EDIT4: Pacifist option and individualistic militarist options work too.
> in the event file the only difference I spot is that xenophile and xenophobe option starts:
> (1tab) option = {
> (2tab) name = mem_eager_traders.5.xenophobe
> (3tab) trigger = {
> and the other options:
> (1tab) option = {
> (1tab) name = mem_eager_traders.5.individualist
> (2tab) trigger = {
> Less space before the name = 
> (when you press tab to shove the line a bit to the right)
> seems the forum cannot display the formating correct even when in the edit window it seems right so i wrote the number of tabs you would have to press before the lines.

Fixing this should have top priority right now.

**Comment by tzerrell** [comment]
Fixed in commits 17020a5 through 0eebce4 (although some translations still needed). I'm closing this issue and will put up translations as separate issue.
