### ISSUE TITLE
Eager Traders fires too often

### ISSUE THREAD

**Issue by Elimdur** [MoreEventsMod/More_Events_Mod_Beta#162]
As the title says. I either got unlucky or it is working like this but i got it everytime i got to know a new species with the according traits. We should add a random into that event so that it only pops up at hmm lets say 30% chance otherwise nothing happens. If it pops up every time it very fast looses its flavor.

Discuss :)

**Comment by tzerrell** [comment]
I haven't played enough normal games of Stellaris recently to know, but I agree that the event happening with every appropriate species is much too often.

**Comment by Deltasquid** [comment]
All of the trader events were meant to fire as soon as you neighbor an AI type of the relevant personality, but that was just an assumption when I first wrote the event. It's just that a lot of AI are peaceful traders, it seems. I can look into adding a percentage of possibility this week to make it less repetitive.

**Comment by tzerrell** [comment]
I believe this has only been left open so long to confirm the spawn rate reduction feels appropriate. I'm going to close it on the principle that if we haven't heard anything about it yet, it's fine, but feel free to reopen if I'm wrong.
