### ISSUE TITLE
Three midgame events need testing

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#165]
@asnys wrote three midgame events that need testing. If I understand how his debug event works correctly, you can test them by running `event asnys.0` and then waiting for things to happen in your capital system.

**Comment by Deytron** [comment]
I found two new issues : 

Issue #1 : The localisation aliases are wrong. For example : `[event_target:ex_planet.GetName]` should be `[ex_planet.GetName]`

Issue #2 : After finishing the special project of mem_ex_planet, nothing happened. No popup finishing the event.

**Comment by Deytron** [comment]
With Asnys' fixes in place, I confirm that the three events are now working properly. Closing issue since the fixes are now merged into `dev` .
