### ISSUE TITLE
Catacombs anomaly - needs translation

### ISSUE THREAD

**Issue by Hoeya** [MoreEventsMod/More_Events_Mod_Beta#166]
Wrote my first anomaly for the mod. Level 3 anomaly. 

Level 3 anomaly. Intended for barren and Frozen worlds only, it should add either 4 society research, 4 energy research, or 500 minerals for xenophobics. It also has a critical failure that will result in the death of your scientist, or a failure that does nothing. 

Testing : add_anomaly mem_catacombs_category

**Comment by Deytron** [comment]
Testing successful, now needs translations

**Comment by tzerrell** [comment]
excellent

**Comment by Deytron** [comment]
Now translated to French

**Comment by tzerrell** [comment]
This seems to be as translated as any other standard event, so I'm closing it.
