### ISSUE TITLE
July 30 Meeting Agenda

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#169]
We're meeting at 3 pm UTC on Saturday on Discord; this issue is for discussing the agenda of our meeting.

Possible topics (I don't think we necessarily need to discuss any of these, but they are worth considering):
- We've now implemented the issue tracker we discussed at our last meeting. Is it working well for us?
- We have a number of Discord channels that are essentially deprecated at this point (#finished_events, #list_of_ideas, #bug_reports) as their functions have been taken over by the issue tracker. Other channels we could port to the wiki if we wanted (#finished_events, #next_release_info, #translator_list, #important_links). Do we want to get rid of some of these channels?
- Our team has grown substantially since our last meeting (55 members as I write this, compared to I believe fewer than 30 at our last meeting). Has this led to any difficulties or opportunities we should discuss?

Also, not particularly critical generally but significant to me: I will be unavailable most of the next two weeks for my wedding. Is there anything that only I know that the team will need during the next two weeks? I've mentioned everything I can think of (which amounted to how we do releases), but I may not be thinking of everything.

**Comment by nCrazed** [comment]
You could probably move the #importan_links channel to a wiki page.

**Comment by tzerrell** [comment]
Indeed we could. Added.

**Comment by ghost** [comment]
Yay, someone is getting married soon! ;) <3

**Comment by tzerrell** [comment]
:D Thank you!

**Comment by tzerrell** [comment]
Another possible topic: we created a beta branch and made a beta release to the forums, but it received little attention (only a couple hundred views and few bug reports). Do we want to continue to do beta and stable releases, or do we want to do just stable releases?

**Comment by Elimdur** [comment]
We should also discuss our focus for the next release (after this weekend´s one).

Which big projects should get finished?

We still have the brainworm event pending, ancient robots is not finished as well.
We need to get the current state of what is finished and what has still to be done into our git wiki. So more than one coder can work on it.

**Comment by wtlnd** [comment]
I will not be able to attend, as I will be occupied at work and unable to reach a computer at that time.
