### ISSUE TITLE
Science convention has flow problems

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#171]
Something bizarre is happening internally in the science convention event. I don't know what it is yet, but in trying to enable the player to receive science convention invites from the AI I have inserted test events and they reveal that different events are being called than the code seems to expect. See c219e386 for details.

There is a good chance this will need to be resolved before we can address some or all of #77, #78, #142, or #143.

**Comment by tzerrell** [comment]
The `science-convention` branch (up through 8642baa) should address this, but needs to be tested.

If you want to test, load that branch, run modify the line `@mem_science_convention_mtth = 600` in `events/mem_science_convention.txt` to `@mem_science_convention_mtth = 2` (just for ease of testing) and play for a while and see if you notice anything odd about the science conventions that spawn.

**Comment by Deytron** [comment]
Actually testing the branch : 
- For your information, `@mem_science_convention_mtth = 600` was at `6000` and not `600`
- After a few months in the game, the Science Convention spawned
- SPOILER : Everything is working properly.
