### ISSUE TITLE
Matrix like idea for a tomb world anomaly

### ISSUE THREAD

**Issue by Elimdur** [MoreEventsMod/More_Events_Mod_Beta#188]
Anomaly

Our survey team has found an ancient structure on this devastated world which is still intact. Further investigation is needed.

Research text

This ancient building complex is being maintained by some rudimentary AI. Our team was not hindered to enter the building and the computersystem did not seem to take any notice of them at all. Deeper inside the complex a shocking revelation awaited our scientists. Thousands of humanoids confined in some sort of pod-like structures and connected to the central computer. They show very high levels of brain activity. The systems seems to keep these inhabitants alive while being confined in the pods even breeding replacements to compensate losses. Chief scientist [name] believes it will take some time to study the databases and find out what the meaning of this place is.

Project finished text

Further investigation of the stored data revealed some shocking details about this complex. It once was some sort of prison as well as a science institute specialised in neural connections and AI research. Their greatest triumph backfired horribly when the selfaware AI decided to do its own research and purged the entire planet of life except for its own assets. From then on it became more and more passive, creating multiple layers of realities for its prisoners to experience and to keep them pacified believing to live a normal life unaware of the truth of their situation. The AI itself has become obsessed over the idea of being just a part a program in another plane of existence and ceased any outside interactions ever since.
###### 

this is not finished yet. If anyone has ideas what to add or how to make the text better, just tell me.

**Comment by htrp** [comment]
Choices should be for a 1) special project communicate with the AI (requires 1 scientist)
2) special project to Shut off the ai (requires 1 troop transport?)
3) leave it be - creates tile blocker with energy adjacency  bonuses

Thoughts?

**Comment by htrp** [comment]
Choices should be for a 1) special project communicate with the AI (requires 1 scientist)
2) special project to Shut off the ai (requires 1 troop transport?)
3) leave it be - creates tile blocker with energy adjacency  bonuses

Thoughts?

**Comment by Elimdur** [comment]
In this case more of a science boost instead of energy ;) but it does not sound bad.

I liked the idea of an obscured breach in the forth wall i saw in one of our new asteroid events.

**Comment by Elimdur** [comment]
https://www.youtube.com/watch?v=wSVlOAocn8E

Hahaha I just watched that one and it turns out my neural network for massive computing power idea was the original idea of the matrix creators xD Then the film studio thought that would be too confusing for the audience and came up with this ridiculous human battery idea that would never work...

After all this video should be very explanatory for my whole anomaly idea.

**Comment by Elimdur** [comment]
I would say we could use the second building picture we have from the ancient robots event to spawn that laboratory  on that planet with pretty good science values.

**Comment by Elimdur** [comment]
Test the anomaly in Matrix-anomaly branch.

Test if the anomaly spawns regularly. You can use this system initialiser for testing purposes. Its a starting system that spawns many tomb worlds in your homesystem. https://cdn.discordapp.com/attachments/184216895455494145/213036206685028353/mhs_testsystem.txt

Test if all the ouctomes of the initial anomaly research work.

After this there is a special project that ends with an event popup + some research and the placing of a special building on the planet that has 3 research in all three categorys + +2 adjacency bonus to all three categories.

Watch out for any typos and report them please.

**Comment by Elimdur** [comment]
Ready for release with next update.
