### ISSUE TITLE
Ancient_Robots_2 Needs Completion

### ISSUE THREAD

**Issue by ghost** [MoreEventsMod/More_Events_Mod_Beta#190]
The ancient_robots event sequence needs testing.   **THIS IS IN THE ANCIENT_ROBOTS_2 BRANCH, NOT ANCIENT-ROBOTS.**   Decided it made more sense to make a new branch so it could be easily merged into dev.   Here's the debugger notes:

EVENT OVERVIEW:

The event has a chance of firing if you have a colony world with a mountain range tile_blocker which has not had any other colony events (so this cannot happen on the same planet as, e.g., Subterranean Civilization). When the event fires, one of your mountain range tile_blockers is made unremovable, and a special project (requiring a science ship) is created to scan the planet for ancient ruins.

Completing the first special project gives you an invitation to a second special_project to excavate the mountain, at a cost of 200 energy and minerals. It also replaces the mountain range with a strange_mountain tileblocker, with different art. You can either accept, say you want to be asked again later, or say you don't want to do it at all. If you accept, either on the first time or later, a second special project (not requiring a science ship) is created to do the excavation. Completing the second special project triggers the rest of the event sequence. If you say you never want to do this and stop asking, a long time period passes, and then you get an event saying a group of private investors went ahead with the project without your help, triggering the rest of the event sequence.

Either way, whether you do it yourself or a private group does, two things happen. First, you gain access to a special project to reverse-engineer the robots which, on completion, gives you some progress on the Synths tech choice. Second, one of two things then happens: either the AI is friendly, or it is unfriendly. If it is friendly, the strange_mountain is replaced with an AI factory building which provides significant bonuses to the planet. After a period of time, however, the AI eventually destabilizes and goes rogue. In addition, if you dismantle or replace the AI factory, the AI goes rogue immediately.

Once the AI becomes unfriendly - either immediately or after a period of time - the AI factory building is replaced by an AI factory tile_blocker (since you can't use it at this point), and a group of eight super robot armies swarm out to attack. If your defenders are defeated, they begin purging the population of the planet one at a time at a relatively slow rate.

Once the first swarm of robots is defeated, a special project is created to lay siege to the final AI citadel. This requires a minimum of eight assault armies to complete. Once it is completed, a second, larger swarm of super robot armies emerges.

If the second swarm defeats you, the AI wrecks the planet: the entire population is killed and the planet is changed to a tomb world.

If you defeat the second swarm, you bring the AI back under control. The AI factory tile_blocker is turned into an AI factory building again, and you gain the ability to manufacture super robot armies. You can only make four of them, however.

USEFUL DEBUG EVENTS:

Firing the event "asnys.16" from the console will immediately place a Mountain Range tile blocker on your capital planet and begin the event sequence.

KNOWN ISSUES:

1: Change trigger to accord with other colony events.
11: What if the planet is invaded by someone else during the sequence?
41: Art not yet uploaded for hostile AI factory - it will look like a random tile blocker.

**Comment by Lukasmar** [comment]
Tested. everything works well

**Comment by tzerrell** [comment]
Was this ever tested?

**Comment by Lukasmar** [comment]
Yes, I tested it. a few things have been fixed, but i don't know the current state of it.

**Comment by tzerrell** [comment]
Ok, I'm going to guess that the "known issues" remain unresolved, and leave this open for asnys to come back to when he wants. I'm going to switch the assignment to him as it's his coding, not your testing, that is needed.

**Comment by Elimdur** [comment]
Did a load of bug fixes.

Have added some text to let the player know how much the digging will cost so he knows why he cannot start it at that moment.

Hopefully the rest is working now with a clean errorlog.

Please report here if you still get errors or a mechanic does not work.

*Check all eventpopup locations
*Check if last project required 8 assault armies to be stationed on the planet
*Check if mechanics still work
****Check if all things are cleared if planet is ceded to other empire while quest is in progress
clearing is started with on_yearly_pulse on action, so it might take a year at the worst before everything is cleared. Eventchain, tileblockers and so on are cleared in this one event.

**Comment by Elimdur** [comment]
Testing has been done by multiple people including Lukasmar, Deytron and myself. I am now confident that the event will be working as designed.

The translations will be flowing in as always anyways. So I will close this issue now.
