### ISSUE TITLE
Incomplete German Translation for Spiritualist Pilgrimage

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#194]
It appears we have a german loc file for Spiritualist Pilgrimage but it is incomplete. See http://steamcommunity.com/workshop/filedetails/discussion/727000451/352788552263152179/?tscn=1471550277#c355043117507433952

**Comment by Elimdur** [comment]
Already fixed, see my comment below his report. Was a messed up file encoding.

---> EVERYONE should run his own version and look into his errorlog. Wrong file encoding will be shown by the error.log explicitely telling which file it is that has the wrong encoding. Every translator should do this as well just to make sure. The game just checks the choosen language files.
