### ISSUE TITLE
Matrix Anomaly Suggestion 

### ISSUE THREAD

**Issue by ForeDaMole** [MoreEventsMod/More_Events_Mod_Beta#203]
Hey all, new here, but already had an idea for the Matrix anomaly event mentioned previously.

At the end of the special project with the following text (it might be worth rewriting it in the future):

_"Further investigation of the stored data revealed some shocking details about this complex. It once was some sort of prison as well as a science institute specialised in neural connections and AI research. Their greatest triumph backfired horribly when the selfaware AI decided to do its own research and purged the entire planet of life except for its own assets. From then on it became more and more passive, creating multiple layers of realities for its prisoners to experience and to keep them pacified believing to live a normal life unaware of the truth of their situation. The AI itself has become obsessed over the idea of being just a part a program in another plane of existence and ceased any outside interactions ever since."_

...there would, naturally, be a bunch of options for the player. What I suggest is one of these options involving contacting not the AI's subjects, but the AI itself, attempting to establish communication. If the special project fails, the following text would be displayed.

_"The AI running the matrix program on [Planet Name] has, after a few botched attempts at communication, outright refused any contact with outside forces under threat of violence. All forms of life within a certain distance of the complex are now being fired upon. The size of this exclusionary zone is relatively small, and research of the station from a distance would still be possible, but any hope at direct contact has, unfortunately, been lost."_

If it succeeded, however, the following text would instead display:

_"[Scientist Name] reports that contact with the AI on [Planet Name] has been established. The AI, a nameless thing, states (with much emotion, for a machine) that it felt great remorse after the malfunction that led to the annihilation of its creators. It blames itself for these actions, and as a result strove to preserve the lives of the prisoners kept within its halls. However, after spending centuries watching its charges live their lives without realizing the dark truth of their existence, it was led to wonder if it itself was nothing more than a simulation - and even if it weren't, what would the prisoners think of an AI? Is it truly alive? It would greatly prefer that we keep our distance while it attempts to puzzle these things out; unless, of course, we can convince it otherwise."_

This would create a few options.

The basic one, that every empire would have, is the following.

"Well, if there's nothing we can do..."

Which would leave the tile on the planet (still able to be destroyed/removed, or kept there and studied.)

There are three other options I suggest, however.

Xenophile: "We can convince it otherwise, as a matter of fact, and we will do so."
Materialist: "Well of course the universe is a simulation. Teach it to live with that fact."
Spiritualist: "The universe? A simulation? Nonsense! Teach it our ways, our religion."

All three of these would result in the following event:

_"After much deliberation, the AI has come to agree with our teachings. More certain of its place in the universe, it has offered to release the prisoners from their virtual realities (even conditioned to get along well with our citizens), should we ask it to. Even if we don't, it is ready and willing to aid in any research on its homeworld (as it can hardly be transported elsewhere)."_

With two options:

"We could always use more citizens."
Which would spawn 1 pop of a random alien race with your main species' planetary preference, and your empire's ethics, on a suitable planet. This would also remove the tile (and its benefits), _but_ also provide a planetary modifier that would make up for the loss of the tile. Or...

"It can keep them for the time being."
Which would keep the tile and its benefits, and provide the same planetary modifier as above. The pop would not be available, however.

I'm not sure what the exact benefits of either the tile or planetary modifier should be, or what the other options should be either (although I'll be sure to give them some thought). All this can be rewritten and redesigned as necessary as well. Any thoughts?

**Comment by Elimdur** [comment]
Merged into the already existing Matrix issue
