### ISSUE TITLE
New Anomaly: "Living Asteroid"

### ISSUE THREAD

**Issue by ForeDaMole** [MoreEventsMod/More_Events_Mod_Beta#204]
This is a proposed anomaly.

This anomaly would only occur on asteroids, preferably ones without a deposit of any kind already.

Upon discovery:
**Unusual Energy Readings**
_“Preliminary scans of [Asteroid Name] have shown strange readings. Both it and the smaller surrounding asteroids display energy readings that are not expected from such objects. Furthermore, [Asteroid Name] is covered in patches of strangely coloured and textured material.”_

The anomaly level should be something low like 1 or 2,  with a low failure chance (10%, maybe?)

Upon completion:
**Living Asteroids**
_“Although [Scientist Name] insists that the term is not accurate, the crew of the [Ship Name] have already begun to call [Asteroid Name] a 'living asteroid'. Massive portions of the asteroids are home to colonies of hyper-resilient lichen, unlike any form of fungi found on terrestrial planets. Like all lichens, these 'living asteroids' are formed of a combination of fungus and cyanobacteria, with this particular species of cyanobacteria being only found with the corresponding fungus – both are entirely new species to the [Empire Name]. While the proposed scientific term for them is “celestial ascomycota”, most media reports and even scientific papers have begun to call them “space mushrooms”. Further study is recommended.”_

Options:
“Interesting.”

> Spawns a +2 Society deposit on the asteroid, replacing anything the might exist there already.

Upon failure:
**Just a hunk of rock.**
_“[Scientist Name] has reported that the unusual energy readings from [Asteroid Name] are nothing more than a scanner malfunction. Furthermore, the textured material on the surface of the planet is simply a vein of metal, which wouldn't even be useful for mining.”_

Options:
“Very well.”

> Nothing happens.

If you have any suggestions or revisions, please feel free to comment with them.

**Comment by Elimdur** [comment]
You should always also include a text for the failure scenario.

**Comment by Lukasmar** [comment]
Tested, clear error log. Polish translation complete.
