### ISSUE TITLE
New Anomaly: "Ancient Satellite"

### ISSUE THREAD

**Issue by ForeDaMole** [MoreEventsMod/More_Events_Mod_Beta#205]
This is a proposed anomaly.

This anomaly would only occur on stars (of any variety, but not black holes).

Upon discovery:
**Deep Solar Device**
_“Scans of [Star Name] show a large object of unknown origin just above the scorchingly hot chromosphere of the star. This object is slowly orbiting around the star at a stable orbit, but how it got there or how it remains intact is as of yet unknown.”_

It should be fairly difficult; level 3 or 4 scientist, high chance of failure (30 to 40%). It's not exactly an easy thing to research, after all.

Upon completion:
**Ancient Satellite**
_“Further study shows that the device close to the surface of [Star Name] is some sort of ancient research station, entirely automated. By all accounts, the device should not be able to remain secure, but an advanced design has protected it from the harsh environment. The satellite, however, is responding to [Ship Name]'s hails, returning information on the dangerous environment of the star – and obeying simple orders given to it, including orders to change its location._

_Two proposals have been made. We could keep the station where it is now, and use the unique location to our advantage, or we could order the station to travel to a higher orbit, so that we could safely study the satellite's composition. Either choice would provide information possibly hundreds of years beyond what we could currently know, but only one can be made. How should we proceed?”_

Options:
“Leave it there and study the star.”

> Spawns a +4 or maybe +6 Physics deposit on the star, replacing anything that might exist there already.

“Bring it up. Let's see what this thing is made of.”

> Spawns a +4 or maybe +6 Engineering deposit on the star, replacing anything that might exist there already.

Upon Failure:
50% chance:
**Coronal Mass Ejection**
_“While getting closer to [Star Name]'s surface in order to further analyze the mysterious object, a sudden solar flare forced the [Ship Name] to retreat. After a series of well-executed maneuvers from the ship's pilots, they managed to safely make it out of the way. However, further attempts to detect the object have failed. How it had survived previous coronal ejections is unknown, but the fact remains that it appears to have been destroyed.”_

> Nothing happens.

50% chance:
**Coronal Mass Ejection**
_“While getting closer to [Star Name]'s surface in order to further analyze the mysterious object, a sudden solar flare forced the [Ship Name] to retreat. Despite their best efforts, the crew of the [Ship Name] could not escape the rapid expansion of solar material, and both the [Ship Name] and the accompanying [Scientist Name] have died. Further attempts to detect the object have failed. How it survived previous coronal ejections is unknown, but the fact remains that it appears to have been destroyed.”_

> Ship and scientist are destroyed, as is anomaly.

If you have suggestions or revisions, please comment with them. I'm particularly interested in thoughts on the anomaly difficulty - I'd prefer it if it were difficult, but that may mean it deserves a larger reward: +3 instead of +2, maybe?

**Comment by Elimdur** [comment]
Ok so if it should have a high failure chance you should think of original failure and critical failure scenarios and write them as well.

Regarding the rewards normal planets can already spawn with bigger deposits and given the risk you want to add to this anomaly I would give it a big reward as well. so 6 would be fitting from my perspective.

**Comment by tzerrell** [comment]
I'm coding the two failure events as a failure and a critical failure rather than as 50% chance of each on failure.

**Comment by tzerrell** [comment]
I've coded and tested this; it's now ready for general testing and translation. You can find it in `dev` and you can access it from console with `add_anomaly mem_ancient_satellite_category`.

**Comment by tzerrell** [comment]
Testing completed
