### ISSUE TITLE
New Event: "Accelerated Evolution"

### ISSUE THREAD

**Issue by ForeDaMole** [MoreEventsMod/More_Events_Mod_Beta#206]
This is a proposed event.

It would occur on colonized planets, after about two years of colonization; somewhere around that time would work well.

Upon occurrence:
**Accelerated Evolution**
_“After several months of living on the world, the colonists on [Planet Name] have noticed something odd about the surrounding environment. Species seen one year were drastically different the next. Upon order of the colony's administration a quick study was performed which showed incredibly fast evolutionary processes from the planet's flora and fauna. A unique process of both sexual and asexual reproduction found in all the species on the world plus a quicker than average life cycle seems to be the cause behind this unusual situation._

_On one hand, repeatedly adapting to the local biosphere prevents the colonists from ever truly fitting in; nothing with a normal evolutionary cycle could. On the other, constant evolution and rapid breeding from the local animals leads to advancements in farming and evolutionary science. Either way, the biosphere of a planet is too complicated to change on this sort of scale. The colonists are saddled with this for good or bad.”_

Options:
“Well, if there's nothing we can do...”

> Creates a planetary modifier titled “Accelerated Evolution” which lowers habitability by 10%, but raises Food output by 10% and Society output by 10%.

Again, if you have any suggestions, please comment them.

**Comment by Elimdur** [comment]
You could have follow up events like dangerous predators evolving as result of your colony's influence of the ecosystem of this planet.

And as before you need failure texts for the anomaly.

**Comment by ForeDaMole** [comment]
Well, it would be an event, not an anomaly, so there wouldn't really be a fail state. That said, that dangerous predators idea you had would be interesting... I'll try writing up something for it later.

**Comment by tzerrell** [comment]
Ready for testing and translation! `event mem_accelerated_evolution.1` to test.

**Comment by Lukasmar** [comment]
Tested & Translated(Polish)

**Comment by Elimdur** [comment]
Ok, tested, so I close this, as translations will be done anyway as soon as a translater gets to this.
