### ISSUE TITLE
New Event: "Tales of Yore"

### ISSUE THREAD

**Issue by ForeDaMole** [MoreEventsMod/More_Events_Mod_Beta#207]
This is a proposed event.

It would occur on any colony, at any time; if possible, it would be best for it to occur some time during the middle of the game, to make up for the lack of content at that point.

Upon occurrence:
**Artifact Cache**
_“As [Empire Name] colonists spread across the world of [Planet Name], expeditions travel out into the frontiers looking for suitable sites for new cities and production centres. Orbital scans can only show so much, after all. One such expedition has stumbled across something far more notable than expected, however._

_A vast cache of ancient books in some alien tongue have been found along with artifacts of many different varieties. From the paintings, statues, and even mummified aliens found within the cache, it appears as though an alien civilization existed on [World Name] some indeterminable time ago. A special project has been issued to decipher the texts.”_

This special project would not require a scientist, but would stall Society research for... 90 days, maybe?

Upon completion:
**Tales of Yore**
_“After deciphering the texts, [Scientist Name] was surprised to find just how much information was found within them. The long defunct civilization, though it never left the late iron age, appears to have had a storied history, with the cache's contents being the artifacts and even heroes mentioned within these sagas._

_These sagas tell tales that took place over thousands of years, and according to radiometric dating, occurred hundreds of thousands of years ago, before the sudden and mysterious disappearance of the civilization. Tales of great warriors, brilliant philosophers, and great glittering cities are all found within their leather bindings. Furthermore, expeditions to where the sagas say the greatest cities were located has revealed ruins that are almost perfectly described by the maps._

_Already the colonists have begun to take more pride in their world, and the media is caught up in a frenzy of adapting the sagas into movies, books, virtual-reality experiences, and even videogames. As for the planet itself, things are looking up.”_

Options:
“Let us praise their grand tales!”

> +25% planet attractiveness.

“Let us praise their ancient wisdom!” REQUIRES MATERIALIST

> +25% planet attractiveness, +10% to all research produced on planet.

“Let us praise their arcane spirituality!” REQUIRES SPIRITUALIST

> +25% planet attractiveness, -10% ethics divergence.

“Let us praise their greatest warriors!” REQUIRES MILITARIST (was MATERIALIST) edit by Malthus

> +25% planet attractiveness, +10% army morale and army damage to all armies produced on the planet.

“Let us praise their beautiful artistry!” REQUIRES PACIFIST

> +25% planet attractiveness, +10% happiness.

Again, any suggestions are greatly appreciated. The bonuses should be meaningful, but not too serious... I'm most interested in suggestions for improving the Materialist and Spiritualist special options, as I think they might be too powerful and too weak, respectively.

**Comment by Elimdur** [comment]
>  in some alien tongue, easily deciphered, 

hmm i think a bunch of texts in a totally alien language could in no way be "easily" deciphered. 
This should warrant a special project at the colony either with a scientist having to go there or a country project without the need of a scientist but a project nonetheless. So we will need a text for this as well.

**Comment by tzerrell** [comment]
This is now coded and tested by me and so is in `dev`. This needs additional testing: Test with `event mem_tales_of_yore.1` with one of your planets selected.

**Comment by tzerrell** [comment]
Working as intended according to @Deytron 's testing.
