### ISSUE TITLE
New Anomaly: "Molten Core"

### ISSUE THREAD

**Issue by ForeDaMole** [MoreEventsMod/More_Events_Mod_Beta#208]
This is a proposed anomaly.

It would only occur on Molten planets.

Upon discovery:
**Seas of Fire**
_”[Scientist Name] reports that, like all molten worlds, [Planet Name] is covered in seas of lava. However, something is clearly unusual about this particular planet, visible even from orbit. Like the average continental world, around 70% of the planet's surface is liquid, despite all predictions stating the lava should have solidified long ago.”_

The anomaly difficulty should be meaningful but not impossible; level 2, difficulty 20%, maybe.

Upon completion:
**Exposed Core**
_”While all molten planets have easy access from the liquid outer core to the surface, [Planet Name] seems to have taken this to the next level. Almost 40% of the planet's surface is exposed to the outer core, which has resulted in the vast seas that provoked the study. Probes can easily be launched to explore the centre of the planet, shedding new light on planetary geology that would require costly mining efforts on any other world. This makes [Planet Name] perfect for research efforts.”_

Options:
“Good to hear.”

> Places a +2 (+3, maybe?) Engineering research deposit on the planet that replaces any other resource deposits.

Upon Failure:
**Solidifying Seas**
_“A report from [Scientist Name] on the lava seas of [World Name] shows that their presence is nothing more than a fluke. Already the surface is beginning to cool down, and it is expected that within a few years the world will have the same lava-to-land ratio of the average molten world.”_

Options:
“Very well.”

> Nothing happens.

As always, if you have any suggestions, please comment with them. I'm still getting used to the intricacies of writing events and anomalies so if there's anything I've done wrong/you feel the event might be unbalanced, just tell me.

**Comment by tzerrell** [comment]
You cannot reference the scientist / ship / empire / etc names in the original anomaly text because anomalies can be spawned without knowing who will discover them (you can reference the planet name because anomalies _are_ always spawned at a specific stellar object). I'm therefore cutting the introductory phrase so the first sentence reads "Like all molten worlds, [Planet Name] is covered in seas of lava." Let me know if you want a different revision.

**Comment by tzerrell** [comment]
This is now implemented and tested by me, and so is in the `dev` branch. It needs one more tester to be ready for `stable`. Test by running `add_anomaly mem_molten_core_category` with a planet selected, then survey. There is one success and one failure event possible; both need to be tested.

**Edit:** This is ready for translation.

**Comment by ForeDaMole** [comment]
No problem; I'll avoid adding references to things in the anomaly discovery text in the future.

**Comment by tzerrell** [comment]
Testing is complete so I'm closing this issue.
