### ISSUE TITLE
New Anomaly: "Crystal Pyramid"

### ISSUE THREAD

**Issue by ForeDaMole** [MoreEventsMod/More_Events_Mod_Beta#209]
This is a proposed anomaly.

It would only occur on Frozen planets.

Upon discovery:
**Strange Lights**
_“At night time on [Planet Name], a massive glowing light can be seen under the transparent surface, kilometres in size. Whatever is creating this light must be capable of producing its own energy over a kilometre underneath a sheet of thick ice.”_

This would spawn a level 3 anomaly with 33% failure rate.

Upon failure:
**Sudden Discharge**
_“As if responding to [Scientist Name]'s efforts, the glowing light underneath the ice sheets of [Planet Name] suddenly glowed brighter than ever, before suddenly disappearing. A massive pyramid shaped cavity was found in the ice where the light originated from, implying whatever was once there suddenly ceased to exist. Whatever the reason behind its disappearance, the [Science Ship] managed to collect a treasure trove of data and energy from the brief and sudden discharge.”_

Options:
“Well, stranger things have happened.”

> Grants 100 Energy and 200 Physics research to the empire.

Upon success:
**Crystal Pyramid**
_“Underneath the surface of [Planet Name], the source of the strange light has been discovered. A vast, perfectly smooth pyramid made entirely out of transparent, colour-changing crystal is where the light emanates from, located deep below the ice sheets. How the pyramid got there, how it's creating the light, and how long it has remained there is as of yet unknown, and will likely remain unknown until direct contact with it can be made. A special project has been issued to further study the pyramid.”_

This would generate a special project which requires a level 4 scientist and take a few months at the least, a year at the most.

Upon completion, one of the following would happen:

75% chance:
**Stranger Things**
_“After reaching the pyramid underneath [Planet Name]'s surface, [Scientist Name] has issued a report on the device's nature. It appears to be made of a material unlike anything else, which has resisted all attempts to even slightly damage the surface. There appears to be no pattern to the waves emitted by the pyramid, and yet they provide a great source of data for our scientists. While there is no end to the philosophical debates created by the strange object, the only real value appears to be studying it further.”_

Options:
“Some things are simply beyond our current understanding.”

> Spawns a +4 Physics deposit on the planet, replacing any deposits already present.

25% chance:
**Crystal Kinship**
“The moment the mining team led by [Scientist Name] reached the pyramid, it glowed a brilliant shade of red. Against [Scientist Name]'s hurried orders, one of the miners placed his clutching appendage upon the pyramid – at which point it suddenly disappeared. At that very moment, a group of crystalline entities appeared just as suddenly as the pyramid vanished, in orbit around the planet.”

Options:
“That can't be good.”

> Spawns a few Crystalline Entities in orbit around the planet.

As always, if you have any suggestions, please comment with them. I'm still getting used to the intricacies of writing events and anomalies so if there's anything I've done wrong/you feel the event might be unbalanced, just tell me.

**Comment by Elimdur** [comment]
“At night time on [Planet Name], a massive glowing light can be seen [originating from] under the transparent surface, kilometres in size. Whatever is creating this light must be capable of producing its own energy over a kilometre underneath a sheet of thick ice. Definitely not an easy task.”

This sounds a bit too much like your scientists already asuming something they have no proof of by this time. ("Definitely not an easy task" this already implies that something of someone is doing this on purpose despite the possibility that it might be an odd but natural occurrence after all.)

" a material unlike anything else, which is completely indestructible, but has no density (and therefore no gravitational pull). " how can a material have no density but still a form and can be touched? also i would be very reluctend to use phrases like "completely indestructable" This is something a marvel comic can state. In science a claim has to be proofed. Without beeing omniscient you cannout know that something is indestructable. you can only say that there is no known way of destroying something.

"No matter was found where the light had been originating from, but a massive pyramid shaped cavity in the ice was discovered, implying whatever was creating the light suddenly ceased to exist. " No matter sounds like vacuum... maybe you could instead write about a giant pyramid shaped cave inside the ice,

**Comment by ForeDaMole** [comment]
Alright, I updated the text to reflect your advice. The object is supposed to be a bit otherworldly (the game definitely isn't hard scifi, and the Unbidden are a good example of extra-dimensional weirdness), but complete indestructibility was probably the wrong way to describe it. Thanks for the feedback.

**Comment by Tuttu** [comment]
The anomaly is ready for testing as I said on Discord. The branch is called **crystal-pyramid** and you can use **mem_crystal_anomaly_category** to spawn it.

**Comment by Lukasmar** [comment]
Tested. Clear error log.

**Comment by tzerrell** [comment]
Merged into `dev`
