### ISSUE TITLE
New Anomaly: "Command System"

### ISSUE THREAD

**Issue by ForeDaMole** [MoreEventsMod/More_Events_Mod_Beta#210]
This is a proposed anomaly.

This would occur only on Tomb worlds.

Upon discovery:
**Seismic Readings**
_“Seismic readings of this world have shown unusual movement far underneath the surface. While not even close to the severity of an earthquake, the regular and constantly moving activity has puzzled our scientists.”_

This would spawn a level 2 anomaly with a failure chance of 20%.

Upon success:
**Subterranean Command System**
_“[Planet Name] became a tomb world some 30,000 years ago according to scans of the radiation in the atmosphere. Under the ruins of cities and major military installations of one of the world's largest previous nations can be found massive elevator shafts leading to a subterranean network kilometres under the surface._

_[Scientist Name] reports that this network of tunnels and stations is some kind of massive railway. It would appear that its creators intended for the railway, which they called the “Command System”, to be used as a kind of fallout shelter. By continually moving, the Command System could avoid attack from earth-penetrating weapons or “EPWs”. However, the railway's creators seemed to have vastly underestimated the length of a nuclear winter as well as the long-term inhabitability due to nuclear fallout; after an average period of eighty years, each of the trains ran out of supplies, with their crews dying shortly after._

_Now, the abandoned trains rattle around below the surface of [Planet Name], still functional despite their incredible age. While the technology that went into them is outdated by our standards, studying the methods used to keep them running tens of thousands of years later could provide us with plenty of valuable information.”_

Options:
“Fascinating.”

> Spawns a +2 Physics, +2 Engineering deposit on the planet, replacing anything already present.

Upon failure:
**Phantom Readings**
_“After much deliberation, [Scientist Name] and the crew of the [Science Ship] have come to the conclusion that the seismic readings from [Planet Name] are due to nothing more than a malfunctioning seismometer. On the plus side, this taught [Scientist Name] to be more careful in the future when researching anomalies; next time, this kind of oversight might lead to someone's death.”_

Options:
“Fool me once...”

> Scientist gains the “Careful” trait.

**Comment by Elimdur** [comment]
_“Like most Tomb worlds, [Planet Name] was created after a fledgling civilization destroyed itself in a nuclear war some 30,000 years ago. 

I do not think it is necessary to tell the player what a tombworld is. Sounds a bit odd to me.

Also it sounds strange that a civ would build such a sophisticated system and would not even test if it is usable at all. Ok there are a bunch of failed megaprojects in this world as well but mostly these are civilian projects. Military operations do tend to be better organized (atleast to a degree)

"when the bombs finally fell, the complicated automated boarding process of the trains led to them launching only after their creators were already annihilated." This sounds unbelievable to me.

you could instead write, that the fatal flaw was, that though they were save inside the trains, after this planetwide nulcear war, they had nowhere to go and waited in their moving HQ for their inevitable end.

**Comment by tzerrell** [comment]
This has been coded and tested by me; it needs additional testing and translation. It is in the `dev` branch and should be tested with `add_anomaly mem_subspace_beacon_category` with a planet/asteroid/moon/star selected.

**Comment by tzerrell** [comment]
Testing completed
