### ISSUE TITLE
New Anomaly: "Subspace Beacon"

### ISSUE THREAD

**Issue by ForeDaMole** [MoreEventsMod/More_Events_Mod_Beta#212]
This is a proposed anomaly.

This anomaly would only occur on asteroids.

Upon occurrence:
**Mysterious Beacon**
_“The asteroid [Asteroid Name] seems to be harbouring some kind of beacon. A consistently repeating subspace ping can be found emanating from its general location at random times, somewhere in the swirling masses of smaller asteroids surrounding the primary one.”_

This would spawn a level 2 anomaly with a failure chance of 20%.

Upon completion:
33% chance:
**Micro Black Hole**
_“The unusual signals coming from [Asteroid Name] have been tracked to a miraculously small black hole, no more than a few kilometres across. Minor asteroids, some no larger than fruit, are regularly sucked past the event horizon. This creates subspace disturbances that, according to [Scientist Name], occur due to the black hole's size. Considering its unusual location, it is highly likely the anomaly was purposefully created for some unknown purpose. Whatever it is, it's worth studying further.”_

Options:
“Fascinating.”

> Spawns a +3 Physics deposit on the asteroid, replacing anything already present.

33% chance:
**Automated Broadcast**
_“According to [Scientist Name]'s report, the mystery signal from [Asteroid Name] originates from a small object embedded in the surface of the asteroid. The object is of alien make, and at irregular intervals broadcasts a subspace signal to several Lagrange points within the system._

_This signal, when decoded, seems to display an automatically created holovid program for some long gone alien race. Each episode is anywhere from one to three hours long, and is a self-contained story set in one of many time periods its creators seem to have gone through, the most advanced being just a few centuries more progressed than our own civilization. As the programs vary wildly in tone, genre, setting, and plot structure, [Scientist Name] has theorized the anomaly was built to procedurally generate such programs. Further study could yield valuable insight into both the alien race's society and our own conceptions about what makes a good story.”_

Options:
“Interesting.”

> Spawns a +3 Society deposit on the asteroid, replacing anything already present.

33% chance:
**Nanobot Asteroid**
_“It would appear that the “asteroid” of [Asteroid Name] is not an asteroid at all, but rather a highly advanced swarm of nanobots. While the exact creator of the swarm is unknown, its purpose has been fairly easily deduced; by sending out a subspace signal, the swarm can detect the echoes of whatever object is present in the system, recording any ships in the vicinity. Whether this was – or maybe even still is – used for surveillance, research, or some other purpose is unknown, but what is known is that in order to maintain secrecy, the nanobots adopt the guise of an unassuming asteroid. Any disturbances on the surface by collisions are automatically repaired by the swarm, before they continue their passive surveillance of the system. By launching missiles and various other objects at [Asteroid Name], we can watch the nanobots go about their work of repairing the “asteroid”, giving us a glimpse of nanorobotics far advanced beyond our current understanding of them.”_

Options:
“Fascinating”

> Spawns a +3 Engineering deposit on the asteroid, replacing anything already present.

Upon regular failure:
**Subspace Anomaly**
_“The subspace signals originating from [Asteroid Name] appear to be originating from nowhere at all. They spontaneously generate from the exact centre of the asteroid, and [Scientist Name] has been unable to find anything out of the ordinary in the region. While certainly fascinating, the signals could easily be replicated in a laboratory, and with no culprit in sight, it looks as if the asteroid has no more secrets to give up.”_

Options:
“Some things are just beyond our current understanding.”

> Nothing happens.

Upon critical failure:
**Abandoned Mining Drones**
_"It would appear as though the subspace pings from [Asteroid Name] were emanating from some kind of automatic mining station deep under the asteroid's surface. The beacon is an emergency signal, requesting aid from one of the station's allies. Unfortunately, the [Empire Name] is not one of these allies, and the station and its drones are equipped with weapons to defend their resource extraction operation. They have already opened fire on the [Science Ship]."_

Options:
"Oops."

> Spawns an Ancient Mining Station next to/on the asteroid, as well as a small fleet of Ancient Mining Drones.

NOTE: It may be prudent to rework the rewards for this anomaly, as all three of the possible outcomes should probably give more than just +2. If that's the case, however, it may also be wise to rework the failure to make it more serious; perhaps the signal is being broadcast by a dormant Ancient Mining Drone station, which is reactivated by the scientist.

**Comment by tzerrell** [comment]
I will indeed increase the rewards to at least +3. My preferred option for the failure would be to have both a failure and a critical failure for this event. The failure could be as is, the crit fail could be something like the reactivated ancient mining drones you suggested.

**Comment by tzerrell** [comment]
This has been coded and tested by me; it needs additional testing and translation. It is in the `dev` branch and should be tested with `add_anomaly mem_subspace_beacon_category` with a planet/asteroid/moon/star selected.

**Comment by tzerrell** [comment]
Testing completed
