### ISSUE TITLE
New Anomaly: "Abandoned Factory"

### ISSUE THREAD

**Issue by ForeDaMole** [MoreEventsMod/More_Events_Mod_Beta#214]
Abandoned Factory
This is a proposed anomaly.

This anomaly would spawn only on Barren or Cold Barren worlds.

Upon occurrence:
**Unusual Structure**
_“A large complex of what appear to be strange rock formations are located near the equator of [Planet/Moon Name].”_

This would spawn a level 2 anomaly with a 33% chance of failure.

Upon completion:
**Abandoned Factory**
_“The rock formations on [Planet/Moon Name] are not rock formations at all, according to a survey by Science Officer [Scientist Name]. They are, in fact, some sort of automated mega-factory, constructed by unknown makers, and abandoned long ago judging by its rundown state. Despite being far too decayed to be repurposed for our own needs, further study of the complex could be useful for our own factories and automation systems.”_

Options:
“Intriguing.”

> Spawns a +2 Engineering deposit on the planet.

Upon failure:
**Unusual Structure**
_“The unusual rock formations on [Planet/Moon Name] are just that; unusual rock formations. They appear to be some sort of self-contained badlands, too small for our scanners to have registered as a fully-fledged region.”_

Options:
“Very well.”

> Nothing happens.

**Comment by tzerrell** [comment]
This is ready for testing. It's in `dev` and can be spawned with `add_anomaly mem_ancient_factory_category`.

**Comment by Lukasmar** [comment]
Tested, works fine. Clear error log.

**Comment by tzerrell** [comment]
Closing this as testing is complete and I don't believe our translators use open issues to track their work as we have several languages.
