### ISSUE TITLE
[From.GetName] not displaying the planet's name during the Star Survey Chain

### ISSUE THREAD

**Issue by Deytron** [MoreEventsMod/More_Events_Mod_Beta#215]
Since the new 1.3 update, the event `mem_star_survey.2` is displaying the ship's name instead of the planet's name. This seems to be caused by `[From.GetName]`.

Here's how it looks like in game : 

![planet wrong](https://cloud.githubusercontent.com/assets/20344764/19680102/abdee3b0-9aa4-11e6-8a68-e813aaccc4c2.PNG)

**Comment by tzerrell** [comment]
This specific bug should now be fixed (in all 5 languages this event is translated into -- although I only tested English), but I'm going to leave this open until @Deytron has finished testing other events, because I'm guessing similar issues lurk in those as well.
