### ISSUE TITLE
LEX Integration

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#219]
We've done a baseline integration of @FrogBucket 's LEX mod into MEM, but we need to make it more thorough. Here are some things to consider (check them off as you do them; comment below if necessary):

* [x] Create test events to make easy to test from pre-existing late game empire saves
* [x] Test Throne Watchers (`mem_test_event.100` with a planet selected and explore the new system)
* [x] Test Gravekeeper (`mem_test_event.200` with a planet selected and explore the new system)
* [x] Test The Conduit (`mem_test_event.300` with a planet selected and explore the new system)
* [x] Revise Throne Watchers English localization
* [x] Revise Gravekeeper English localization
* [x] Revise The Conduit English localization
* [x] Fine-tune weapon stats
* [x] Consider removing leviathan country buff
* [ ] Look for other MEM events that could take advantage of these ships

**Comment by Elimdur** [comment]
integration canceled, the mods will stay seperate.

**Comment by Elimdur** [comment]
integration canceled the mods will stay seperate to not infuriate some of these snowflakes in the workshop.
