### ISSUE TITLE
Carcosa opinion modifier should apply to new contacts

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#220]
Currently only applies to empires you knew when choosing the option.

**Comment by tzerrell** [comment]
The fix needs testing: run `event mem_elusive_carcosa.20` with a planet selected in a save game where you have contact with a fallen empire to test.

**Comment by Elimdur** [comment]
There is still another problem that just came to my mind. If for example you liberate planets or a primitive civ becomes space faring after you got the modifier, they won´t ever get the "trustworthy" modifier.

on_pre_communications_established = {
	events = {
		action.7
		action.19
	}
}

We can do it similar to action 7 to put the modifier on not before known empires.
Doing this we can also restore the old mechanic of only giving the modifier to already known countries.

We would also need to set a country flag in case the player chooses this option so we have a chance to trigger the on action correctly.

**Comment by Lukasmar** [comment]
fe didn't get any opinion modifier. every other empire have opinion modifier

**Comment by Elimdur** [comment]
Fixed it in dev. Checked if it is working and everything seems to be fine.

Lamil should still take a look at it just to make sure i did not overlook anything.

**Comment by tzerrell** [comment]
Looks good to me.
