### ISSUE TITLE
Get a new Steam title graphic

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#221]
There are several options:
* Use an old graphic from @FrogBucket 
* Have @FrogBucket create a new graphic
* Find an appropriate CC-BY or public domain graphic
* Find a graphic and get permission from the author to use it

**Comment by Zebogo** [comment]
What resolution and details (information, style) do we need?

**Comment by tzerrell** [comment]
Style would ideally match the Stellaris event image style. Resolution is flexible, but ideally 400 tall by 600 wide or more. It doesn't need any information on it (indeed, the base image should have no info), but we will be throwing a banner on it giving the current version (similar to what we're doing with our current image).

**Comment by tzerrell** [comment]
Unless someone has a better idea (and if you do please speak up!), I propose we use this image for the title image: [mem_ancient_robots_eventpic_04.dds](https://github.com/MoreEventsMod/More_Events_Mod_Beta/blob/dev/gfx/event_pictures/mem_ancient_robots_eventpic_04.dds)

**Comment by Elimdur** [comment]
https://cdn.discordapp.com/attachments/184216895455494145/274222574400045056/more_events_mod_1-9.jpg

This should work for us as the other picture would not be big enough anyway. Of course if we ever find a better one we can still change it.
