### ISSUE TITLE
Anomaly: Ancient graveyard

### ISSUE THREAD

**Issue by ViolentBeetle** [MoreEventsMod/More_Events_Mod_Beta#230]
A simple flavour L1 anomaly idea.
Spawns on barren planets.

**Initial description:**
Sensors are registering strange readings from a large valley on planet's surface, as if it is filled in regular grid pattern with small metallic spikes. Too small to properly discern from orbit, they might require a closer look.

**Success:**
Surveyors discovered almost a billion upward-faced primitive pulse rifles, each muzzle topped by what appears to be a visored helmet of some alien species dotting the valley, as if marking resting place of countless soldiers fallen in an ancient battle. Although well-preserved in almost vacuum, primitive rifle design is of little interest to our scientists. Deep scanning into ground underneath also revealed nothing of value. Whatever happened here aeons ago, we might never know.

**Generic confirmation:**
Let them rest in peace.
**Xenophobe confirmation:**
More dead xenos, huh?
Both give 100 influence.

**Failure:**
It appears that strange pattern was nothing but an echo caused by an improper sensor calibration. Second sweep revealed nothing of interest.

**Comment by BLimmie** [comment]
Do you have an idea of what you want the titles of the event triggers to be? I put fillers in the .yml file in the ancient_graveyard branch.

**Comment by ViolentBeetle** [comment]
Changed your titles more to my liking (Except for one that is really fitting). I hope I didn't break anything.

**Comment by BLimmie** [comment]
Did you sync it already?

**Comment by ViolentBeetle** [comment]
I guess I did? Seeing that you merged something in the branch? New to GitHub, sorry. 

Coders in chat remind:  If you make anomalies, make sure to connect them to the correct story event. This is used when finding alien life, alien spacefaring civs, remnants the first time.

**Comment by Lukasmar** [comment]
file uses wrong encoding UTF-8 without BOM, it should use UTF-8.

**Comment by BLimmie** [comment]
Which file?

**Comment by Lukasmar** [comment]
mem_ancient_graveyard_l_english.yml

**Comment by Lukasmar** [comment]
localisation files must use UTF-8

**Comment by Lukasmar** [comment]
already fixed encoding and tested this anomaly. clear error log. failure risk at 1* scientist is 0%, i think you should change it to at least 10%.  getting from L1 anomaly 100 influence is high reward in my opinion.

**Comment by BLimmie** [comment]
It is now changed to be less overpowered
