### ISSUE TITLE
New Anomaly: Engineered Wildlife

### ISSUE THREAD

**Issue by R3miel7** [MoreEventsMod/More_Events_Mod_Beta#232]
Please let me know what you think or if you have any suggestions for improvement.

-------------------

## **Lv 3 Anomaly: Engineered Wildlife**

Spawns on any non-tomb habitable world.
65% chance of success
35% chance of failure

**Upon Discovery**
_Scans indicate the wildlife of [planet_name] are quite unusual. Further study is needed to see how this may impact potential colonization efforts._

## Upon Completion: Success

**The wildlife is… cute?**
GFX_evt_animal_wildlife

_The native wildlife of [planet_name] are exceedingly calm in the presence of our researchers. What’s more, every species encountered so far is quite aesthetically pleasing to the crew creating feelings of protectiveness and companionship. While [scientist_name] was originally worried that this may be some pheromone or other alien phenomenon, results show that the animals in question are simply deemed “cute.” The pleasing nature of the animals from [planet_name] is too universal to be a result of natural evolution and the current leading theory is that this world may have been the target of genetic engineering in the past to create some kind of zoo. Regardless, the friendly nature of the local fauna will be welcome if we choose to colonize the planet._

> Removes all ‘Dangerous Wildlife’ tile blockers on planet
> Adds 2 - 3 ‘Alien Pets’ resources to planet

## Upon Completion: Failure

**Hostile wildlife everywhere!**
GFX_evt_animal_wildlife (would be better if it was the image of the 'Dangerous Wildlife' creature.

_The native wildlife of [planet_name] are incredibly hostile and dangerous! Several crew members of the [science_ship] were lost getting samples of the wildlife and every creature is lethal to organic life in some way or another. Genetic sampling of the species we did capture show clear evidence of genetic tampering. [planet_name] was most likely a laboratory of the development for alien bio-weapons which eventually got loose. Whether or not the creatures destroyed their creators is unknown. Regardless, the hostile nature of the creatures will create significant barriers for our colonists if we choose to pursue colonization._

> Adds ‘Hostile Fauna’ celestial body modifier
> Changes all tile blockers to ‘Dangerous Wildlife’
> Adds 2 additional tile blockers of ‘Dangerous Wildlife’

**Comment by Elimdur** [comment]
In case of success maybe mark this planet for a later "Tribble" event ;) https://www.youtube.com/watch?v=Bprgl_4z6gY

**Comment by tzerrell** [comment]
Quick extremely minor comment that stellaris style is to have fail
percentages end in 0 or 5, so probably this should be coded up as 35% (or
30%) fail rate. When you see other final digits in game it's from being
over level or having traits that adjust fail rate.

**Comment by R3miel7** [comment]
Success/Fail percentages adjusted to end in 5's

**Comment by CashewCraft** [comment]
Could this be potentially expanded where a critical failure results in the animal's cuteness being an elaborate trap to lure in prey, killing the science officer?

**Comment by CaligulaCaesar** [comment]
I imagine this never got added, but I can easily do it :)

**Comment by CaligulaCaesar** [comment]
I added this
