### ISSUE TITLE
Observation post event: Sleeper cell

### ISSUE THREAD

**Issue by ViolentBeetle** [MoreEventsMod/More_Events_Mod_Beta#233]
Idea for an event for observing primitive civilization. Can be triggered by both passive or active studies on pre-industrial planet.

**Introduction:**
Our observation post over [Planet] is reporting unusual and alarming readings coming from the planet. They are picking up an energy signature originating from beneath the planet's surface in an isolated region. The strength of the signal beyond anything native technology could produce and is notably similar to our own power plants. More alarmingly, the signature clearly indicates a growing instability in the power source. This will likely end in disaster if we don't act fast.
> Issue a timed special project - Investigate strange energy reading. Requires a science ship.

**If timer runs out:**
80% chance
A massive underground explosion ripped through the crust of [Planet], sending ash and rocks into the atmosphere with power rivaling a supervolcano eruption. Whatever there was to be found at ground zero is now certainly vaporised. Our observation post reports that natives who witnessed the incident are overawed by the catastrophe, and local cultures are experiencing a surge of spirituality born out of fear before the gods' wrath.
> End of chain. Natives are pushed toward spiritualist ethos. Crater tile blocker spawn on a tile.

20% chance
A massive underground explosion ripped through the crust of [Planet], sending ash and rocks into the atmosphere with power surpassing that of a supervolcano eruption. This triggered supersonic pressure waves throughout the planet's atmosphere, a cascading series of massive earthquakes, and smothering plumes of dust and cinders sufficient to send the entire planet into a permanent twilight. This catastrophe has devastated the biosphere and extinguished the native civilization. Whatever we could have found at the ground zero was certainly vaporised. 
>End of chain. Natives are removed and planet type changes to tomb world. Crater tile blocker spawn on a tile

**If project complete in time: Underground vault**
Following the energy signature [on Planet] required precise drilling from our science team but ultimately led them to a vast cavern system. Once inside the team uncovered a large artificial structure deliberately concealed within. The structure was unambiguously built using space-age technology, centuries ahead of what natives should be capable of. Within this structure the crew was startled to find countless sleeping pods lining the walls, containing aliens which are not only unlike the [Name of native race], but also unlike any other species known to us, as well as massive stockpile of advanced military hardware. Yet language used on terminals and labels bears a remarkable resemblance to languages we learned from observing the [native species].

Our engineers in reactor control have assessed the situation, which is rather anticlimactic after the earlier discoveries. Centuries, if not millennia, without maintenance have taken their toll, but with our level of technology stabilizing the reactor should be trivial, especially if we are willing to sacrifice some of our own resources.
_Options:_
>Channel our energy into the vault, fully reactivating it. [Costs 1000 energy. Progress toward "Sleepers Awake"]

>Channel our energy to stabilize and prolong reactor's output and reactivate pods for key personnel [Costs 300 energy. Progress toward "Remnants"]

>Stabilize reactor and allow it to run its own failsafe routines [Progress toward "The Last"]

>[Not xenophile]Too risky. Depower all systems and scrap the vault for valuables [Chain ends. Gain 500 minerals, 300 society and 300 engineering]

>[Xenophobe]Xeno lives aren't worth risking our team. Evacuate and let vault explode. [Chain ends. Gain 100 influence. Trigger one of the failure events]

**Sleepers Awake**
With the influx of energy, lights turn on through the silent corridors of the vault. One after another sleeper pods open. [Our scientist] hurries to the council chambers, where leaders of the sleeper society were stored. There an alien greets [him/her].

[This is a lot of text to revise for English style/grammar and I'm pausing here given that it might be coded as a diplomatic event (which would require a bit of revising for content). -LL]

Establishing communications was not an issue, as language he spoke was related to multiple languages spoken by contemporary [natives]. After learning what is going on, alien told us his story.

Millennia ago his own species has evolved and dominated the planet. Long before they were ready to reach the stars, they advanced their biotechnology and genetics to remarkable levels. Their experiments led them to uplift another species from their planet into sentience to be servants, soldiers and one day perhaps join them as equals. This were ancestors of a species we now know as [natives]. However differences between two species had left to conflict and although scientific knowledge was withheld from the uplifted, they have benefits of numbers and elements of surprise. They have drove their masters to the brink of extinction, just as they were ready to test their first FTL ships, and forced them to seek refuge in a vast underground vault. The vault we have found them in.

"Now there's one thing left to do before we move on" - he concluded.

>Event spawns a single POP of a new species on the planet. They have either xenophile or xenophobe ethos with other being randomized.
> Instantly after this second event fires - one of the two possibilities depending on ethos new species spawned with

**Sleepers Awake - Day of Reckoning [If xenophobes are spawned]**
[natives] might once have been uplifted and able to drive civilization that uplifted them to extinction, but this is no longer a case. What technology they had, they lost without guiding hand of their former masters, forced to build their own civilization from scratch. 

This civilization was no match for weapon stockpiled inside the vault. Gliders and drone strikes killed most of [natives] within hours, leaving the reawakened [new species] as sole masters of the [Planet]. Their leader is now hailing us wishing to discuss his relationship with our empire.

Options:
>[Not xenophile] Invite them to join our empire [Planet is now ours]
>[Xenophobe] Impressive move. Invite them to join our empire. 

>[Not xenophile] Invite them to become our protectorate [Uplift them as xenophobes]

>[Xenophile] Refuse to deal with those genocidal maniacs [Planet spawns a custom empire with xenophobe ethos]
>[generic]We have no interest in taking over this planet 
>[Xenopobe] Impressive move. But we have no need for them 

**Sleepers Awake - Return of Benefactors [If xenophiles are spawned]**
[natives] might have lost most of the technology that their former masters had, but they did not forgot those who first gave them sentience. Their memory lived on, as myths and legends of gods, betrayed by ungrateful ancestors. 

Once [new species] revealed themselves, [natives] rejoiced, seeing their benefactors return from the grave. The bond was forged anew, and leaders of the [new species] promised to never repeat mistakes of the past. Now they are hailing us wishing to discuss their relationship with our empire.

Options:
>Invite them to join our empire [planet is ours now]

>Invite them to become our protectorate [Uplift them as xenophiles]

>[Xenophile] Now both species should forge your own destiny. Don't make the same mistake again. [Planet spawns a custom empire with xenophile ethos]
>[generic] We have no interest of taking of this planet 
>[Xenophobe] We don't need them in our empire 

**Remnants**
Only a few pods have lighted up. Our scientists hurried to extract and stabilized aliens contained in them. 

Establishing communications was not an issue, as language they spoke was related to multiple languages spoken by contemporary [natives]. Not all took news of their species destruction well. Once they overcame initial shock they have told us their story.

Millennia ago his own species has evolved and dominated the planet. Long before they were ready to reach the stars, they advanced their biotechnology and genetics to remarkable levels. Their experiments led them to uplift another species from their planet into sentience to be servants, soldiers and one day perhaps join them as equals. This were ancestors of a species we now know as [natives]. However differences between two species had left to conflict and although scientific knowledge was withheld from the uplifted, they have benefits of numbers and elements of surprise. They have drove their masters to the brink of extinction, just as they were ready to test their first FTL ships, and forced them to seek refuge in a vast underground vault. The vault we have found them in.

"We have no place on this world anymore" - their leader said - "Our species are dead and our own creations are unlikely to take kindly to us. Perhaps you can grant us sanctuary among your people

Options:
>Welcome aboard [Gain 5-star governor, scientist and general of the custom species]

>Sorry, but you belong here. You owe your creations this much [Gain 75 influence. Accelerate native's tech gain]

>[Xenophobe option] We'd rather put you out of your misery, xenos [Gain 125 influence]

**The Last**
Before shutting down, reactor was able to produce enough energy to revive a single pod. Our scientists rushed to it and found an alien who appears to wear leadership regalia.

Establishing communications was not an issue, as language he spoke was related to multiple languages spoken by contemporary [natives]. Upon finding out that he was the last of his kind, alien almost had a breakdown. Once our team could calm him down, he shared his story.

Millennia ago his own species has evolved and dominated the planet. Long before they were ready to reach the stars, they advanced their biotechnology and genetics to remarkable levels. Their experiments led them to uplift another species from their planet into sentience to be servants, soldiers and one day perhaps join them as equals. This were ancestors of a species we now know as [natives]. However differences between two species had left to conflict and although scientific knowledge was withheld from the uplifted, they have benefits of numbers and elements of surprise. They have drove their masters to the brink of extinction, just as they were ready to test their first FTL ships, and forced them to seek refuge in a vast underground vault. The vault we have found them in.

"I don't believe I belong in this world anymore" - he said - "Perhaps you allow me to join you among the stars?"

Options:
>Welcome aboard [Gain a 5-star governor]

>Sorry, we can't allow this [Gain 50 influence]

>[Xenophobe] Why don't we finish the job and put you out of your misery? [Gain 100 influence]

**Comment by R3miel7** [comment]
For the 'Sleepers Awake' path, it may be fun to open up a chat window like from the Gas Giant Dwellers event chain.

**Comment by ViolentBeetle** [comment]
I'd live it for coders to decide if they go to implement it. Writing options more conversationally would not be a problem.

**Comment by tzerrell** [comment]
If someone wants to code a chat window style addition, here are a couple of examples of diplomatic events (what chat window style events are called in the code):

* A simple example is `mem_elusive_carcosa.21`. To see it in action, run `mem_elusive_carcosa.20`, choose the "Use it to redefine our species in the eyes of other nations" option, and wait a few days. (You will need to use a save where you have contact with a fallen empire for it to work.)
* A more complex example is the pair of events `mem_ea_uplifter.15` and `mem_ea_uplifter.16`. You might be able to see these in game just by running `mem_ea_uplifter.15`, but I make no promises it will work right without the preceding events.

**Comment by Elimdur** [comment]
I really like that story. The text has some rough edges, but a native speaker like lamil may help to give it some polishing :)

**Comment by tzerrell** [comment]
Hmm, I didn't realize the initial post doesn't keep its history somewhere. How un-git-like of it. Hope I didn't destroy anything with my revisions :/

Anyway, awesome event, definitely looking forward to having this in MEM

**Comment by ViolentBeetle** [comment]
What did you change by the way?

**Comment by Elimdur** [comment]
Oh already 6 days ago and i did not realize you already made a revision.

I´ll do the coding part for this event. Having all the text pieces in place will make for a nice difference once in a while^^

**Comment by ViolentBeetle** [comment]
Before you start, 3 leaders reward might be a bit excessive?

I was considering nerfing it by either giving them substance abusers (Survivor guilt and all this, need to cope) or custom survivor guilt modifier with similar effect or maybe bump them down to 3 stars?

**Comment by Elimdur** [comment]
or just one leader

**Comment by ViolentBeetle** [comment]
You get one leader for free, sole survivor route, that's why there need to be more leaders in the remnants path.

**Comment by Elimdur** [comment]
maybe you could think about another kind of reward than leaders?

**Comment by ViolentBeetle** [comment]
How about "Remnant advisors" modifier. 
+X% to biology research (If can't modify biology, just society)
Modifier ticks down as they die out one by one.

**Comment by Elimdur** [comment]
hmm maybe a timed + 5 % modifier for 30 years or so
if that is possible

**Comment by ViolentBeetle** [comment]
I suggest +10% if possible to only boost biology, +5% if only society. 30 years later fire an event that says the last of them died and took their expertise with them in grave.

**Comment by Elimdur** [comment]
OK, status report:

- Event spawn works
- project spawn works
- both fails work (changing pop and country ethics + turning planet to tomb world and placing tile blockers

**Comment by ViolentBeetle** [comment]
Ambiguous syntax, does crater spawn in both cases?

**Comment by Elimdur** [comment]
Yep in the soft fail you just get one crater. In the hard fail you get a crater surrounded by radioactive wastelands + some volcanos

**Comment by ViolentBeetle** [comment]
Some additional thought for reward. Regular scientist has +10% to his area, potentially lives very long and adds a bias to the tech. Mimicing numerical bonus to a reward sounds fair, and since it's one of a kind bonus that will run out relatively soon, even +15% seems reasonable to me (AI techs are so much more powerful)

Additionally, they could bring in fraction of Epigenic Triggers, since it's their know-how.

Price for it might need to be bumped, since 100 energy is a bit low.

**Comment by Elimdur** [comment]
I am thinking about offering an alternative option for paymend in case you have not enough energy stored. Similar to the option when dealing with the enclacves to get a negative income modifier for a limited time to get the substract the same energy value over time instead of instantly.

**Comment by ViolentBeetle** [comment]
In terms of fluff, it seems weird. We aren't paying anyone, we need to power the system up now.

**Comment by Elimdur** [comment]
you always have a private sector to pull ressources from and then over time repay. See it as government bonds.

**Comment by Elimdur** [comment]
I´d like to propose a small change. When finding the vault i would like to have som kind of randomness what happens when you use energiy to restore power / shut the vault down.

I would suggest letting the power the systems up option be merged and have a random outcome between remnants, sleepers awake and the last.

If shutting down the systems to scrap the base there might happen something bad, like some pods are activated through the failsafe system and your team is attacked by the sleepers (your scientist dies - have to see how to target him from that point, otherwise they may just try to make the vault explode to take your with them, having a similar outcome as the hard fails when not doing the project but also need new text)

**Comment by ViolentBeetle** [comment]
I would prefer to not randomize here in case players would want to try a specific thing.

As an alternative, let player pump different amount of energy into the system (For example 1000, 750, 500 and 250) which would affect probability of choice between 2 paths (Starting with 100% possibility in favour of Awake, 33% step biasing towards Remnants for each decrease until the last option guaranteeing Remnants) with refusal to pay will always net you The Last.

Scrapping COULD lead to alternative, but I'm not sure what would alternative be, fluff-like. Rescue options would not quite fit, since you just tried to kill them, so it would take an extra branch.

**Comment by Elimdur** [comment]
but replayability is what we should be aiming for, having one option always leading to the exact same result makes it absolutely predictable and in the long run boring.

**Comment by ViolentBeetle** [comment]
You have a point, but as of this moment I'm out of ideas for extra possibilities.

If we are to take it into some completely different direction, I would prefer to make a separate event. And if we stick to the current three, I don't see a point in shuffling them around at random.

**Comment by Elimdur** [comment]
Oh i think i can come op with something while doing the code ;)

**Comment by Elimdur** [comment]
Coding is done.

- [x] Testing every possible outcome for bugs that might have slipped through

- [x] Revision of the texts to get rid of my bad grammar

- [x] Once these are done setting the values for release version and merge to dev

**Comment by ViolentBeetle** [comment]
Reactivation of vault summoned a conversation screen with a single button "What will they do now". It led to an empty dialog box.

I'm not sure what was supposed to happen, but probably not this.
