### ISSUE TITLE
Planetary event/quest chain idea: Food constructor

### ISSUE THREAD

**Issue by ViolentBeetle** [MoreEventsMod/More_Events_Mod_Beta#235]
Idea for event and quest chain. Could use some help with extra tasks for the player.

Event occur on any colony. Series of timed events progressively change planet's modifier, while player must find a way to end this chain.

**A curious discovery**
One of the colonists on [Planet] has made a curious discovery where he stumbled upon a massive alien artefact while exploring outskirts of the settlement. After accidentally activating it, he noticed it producing fine grey dust. Later analysis revealed that this dust is harmless and, in fact, makes very nutritious food fit for consumption by almost any organism. Although it appears to have a short shelf life which makes off-world export infeasible for now, it promises major benefits for local population.
>[Generic] Interesting
>[Xenophile] This a gift from alien intelligence
>[Spiritualist] Truly a divine blessing
>[Xenophobe] We should not trust alien technology
>[Materialist] Carefully, it might be booby-trapped

>Adds "Food dust" modifier to the planet: The planet houses an alien machine that constantly produces nutritious dust for locals to consume. [Food +10%]

**Production outstrips consumption**
Alarming reports from [Planet] where ever growing output of food constructor had reached the level where people can no longer eat it fast enough. Attempts to shut the device down had proven futile - decoded inscriptions of the construct mention "Reesan key" as a mean to deactivate it - however we possess no such thing. Attempts to destroy the machine has also proven futile - its hull seems tougher than any artificial material we know of. Landfills are threatening to overflow and people flee districts surrounding the building where machine is housed.
>[Generic] We need to find a way to shut it down
>[Xenophobe] We should not have trusted alien technology
>[Materialist] What happened to good old "Off" button?

>Replace modifier with "Food dust overflow": The planet is dangerously close to being buried under food constructor's produce. Thin grey dust is flooding the areas surrounding it while winds create unprecedentedly nutritious dust storms [Food +15% Happiness -10%]

**Planet is drowning in food**
Local authorities on [Planet] have officially given up on attempts to contain the situation. Ever-growing output of food constructor has overwhelmed any attempts to dispose of it in landfills or carry it off-world. The entire planet is grey with thick layer of food dust. What's worse is that constructor appears to draw energy from the local grid, hampering its performance.
>[Generic] This is a disaster!
>[Militarist] Looks like it didn't have to be booby-trapped
>[Xenophobe] We should NOT have trusted alien technology!
>[Xenophile] A tragic oversight on creators' part, for sure
>[Materialist] What have science done!

>Replace modifier with "Food dust everywhere": Thin food dust has covered the entire planetary surface, while constructor is draining the energy grid to increase its output with every moment. Edible as it is, the blessing is now turned into a terrible curse for local population [Food +20%, Habitability -10% Happiness -15%, Energy -25%]

**Food tide**
Life on [Planet] has turned into a constant race against the rising food tide, forcing population to constantly move to new heights to escape ever growing produce of the food constructor. Most of the industry had chocked on the fine grey dust covering the planet.
>[Every ethos] Please make it stop!

>Replace modifier with "Rising food tide": Nutritious dust from the food constructor is covering the entire planetary surface with a layer of at least a kilometre thick. Locals might never have to go hungry again, but they can hardly go anywhere at all. [Food +25% Habitability -20% Happiness -30% Energy -50% Minerals -50%]

**Missions to find Reesan key**
Quest is initiated soon after second step is started.
_Or perhaps have any ship to pick up a signature in a new system?_

Our long-range sensors have picked up a faint energy signal resembling energy signature of a working food constructor similar to one in our possession. Although it reached us outside of FTL and whoever operated it are likely long gone, they might have left behind a clue to locate the elusive Reesan key.
>[Generic] We need to investigate as soon as possible!
>[Spiritualist] Saved by a divine providence!

>Issue a special project for level 3 science ship to investigate a barren or toxic planet in a distant system. 

Upon completion:

Following ancient energy trail we have eventually found a massive cargo ship crashed on a desolate world. It appears its crew tried to tow a constructor, still welded to the ship's hull into a star, only have their systems drained of energy mid-flight by the constructor. Dead ship have drifted aimlessly for some time until it was caught into planet's gravity and eventually crashed on its surface. 

What little data we could pull from the dead flight computers revealed that original mission was to deliver the constructor to an asteroid base, in hope that a reclusive alien researcher who owns it would be able to deactivate the constructor. We have copied the coordinates of the base.

If it is any consolation, it appears food constructors do stop working. Eventually.
>We might still have a chance

>Issue a special project for a level 4 science ship to investigate an asteroid

Upon completion:

Our scientists have successfully located an asteroid that was hollowed to house some sort of research station and habitat. Just like the ship before it, its systems are drained of energy while its interior is filled with long-expired food dust. Using miniature drills our science team have successfully dug into the core of the facility and managed to locate former owner of the station, his remains well-preserved in the dust. They managed to extract some data from his digital assistant. It appears he was experimenting on one of the food constructors in attempt to find a way to shut it down, when sudden spike of production has breached the containment and suffocated him. Although he was not able to turn the constructor off, he appears to have deduced the location where designers of the constructor operated.
>[Generic] The Reesan Key is almost within our grasp!
>[Materialist] Miracles of Reesan science await!
>[Xenophile] We can learn so much from Reesan civilization!
>[Xenophobes] Those galactic polluters have some explaining to do

>Spawn a new system called Reesan Operations within player's space with a broken ring world.  One segment is intact, but uninhabitable. Broken segments all produce 1 physics and 1 engineering. Issue a special project to investigate this segment for level 5 science ship. The system is guarded by a powerful drone fleet.

>On the subject of the fleet. Skilled player's opinion would be appreciated. Basic outline: Battleship-Destroyer combo. Relatively few Gatekeeper-class Battleships with energy weapon escorted by large number of Watchdog-class Destroyers, equipped with kinetic weapon. Alternatively equip both with unsalvageable matter desintegrators. Balance between shield and armour. Adding together to 20-30K fleet power. They are passive, but hostile, holding orbit over the surviving segment of ring, but not engaging unless approached. If it's not feasible due to them being to close to the system's edge and potentially getting into fight with those who just jumped in, move them to the star's orbit. Frog agreed to make models in the future.

**Arrival to the system**
We have arrived to a system identified by a dead researcher. Massive ring world is spanning the system. Massive and badly damaged. Powerful technology definitely flourished here once, but this place clearly saw better days. However, not everything is cold and dead. We are detecting a fleet of powerful automatic ships in the system. They are hailing us.
>On screen

**Dialogue with drones:**
Thank you for visiting our centre for customer assistance and support. Unfortunately, our certified services are not available right now, so please keep your distance until manager arrives from off-world to assist you. Please do not approach the facility or you will be destroyed. 

This automatic message was brought to you by Reesan Matter Constructors and Deconstructors. Reesan Matter Constructors and Deconstructors: The past was terrible, this is why we invented the future.

>How long until your manage arrives?
Our services were suspended for INTEGER OVERFLOW years as of the moment, which is slightly longer than usual. I apologize for that. But I assure you, manager will arrive shortly. In a mean time, please tell me if I can make your wait more comfortable.

When such situation arises, we usually offer our clients special cookies made with special recipe. Unfortunately, right now we can only offer you PETRIFIED DUST. Would you like some?

>Why were your operations suspended?
I'm sorry, but I'm afraid I can not disclose this information. Try asking one of our managers, when they arrive. 

>Do you have a Ressan Key?
Of course. If you have misplaced or damaged your Ressan key in the first 100 years of using one of our products, you are entitled for one free replacement. Just provide one of our managers with your name and proof of purchase, and you will receive your replacement shortly.

If you have already received a free replacement, please contact our managers for up-to-date information of replacement cost.

>[Special option for pacifists] There must be a way for us to resolve this peacefully
There is. Just wait for our manager and you will be provided with any assistance you need with as little violent altercations as possible.

>[Special option for militarists] Let us through, or we'll force you!
I'm sorry that you are tired of living and considering suicide. Is there any way I could convince you to reconsider?

>View screen off
Ends the conversation

**After drones are defeated and project complete**
Our science team has searched countless warehouses on the ring world. Among many devices way beyond our understanding we have located a gigantic warehouse filled with what without a doubt are Reesan keys. The rest of bizzare Reesan contraptions will provide us with invaluable insight for years to come.

News of recovery of the device has spread across [planet] as the calamity has passed. With Reesan key delivered and inserted into the constructor, grey nutritious nightmare is finally over as the device appears to have been drained of all energy.
>It's finally over

> Reward: +6 science and engineering on surviving ringworld segment. The modifier on the affected planet is replaced with "The dust had settled": "With the food constructor shut down for good, life on the planet is returning back to normal. The layer of decomposing dust have proven to be a very good fertilizer, and the planetary ecosystem flourishes" [+10% food, +5% habitabilty]

**Epilogue**
Final event fires 3-5 years later

Amazing news from the [PlanetName]. The thick layer of food dust that was covering the planet has effected dramatic change on planet's ecosystem. With influx of easy and abundant energy, life on planet flourished and biodiversity skyrocketed! This dramatic change lead to the planet's official reclassification into a gaia world.

>[Generic] Amazing
>[Spiritualist] Spirits work in mysterious ways...
>[Xenophile] We should be forever grateful to the enigmatic Reesans

**Possible extra option - for those with Leviathans DLC**
Add extra button to curator enclave conversation

>Do you have a Reesan Key?
Looks like you are having trouble with one of the Reesan food constructors? We know about several such incidents through history.

Alas, we do not have a Reesan Key, and do not even know where to start searching for one. Reesan High Science had flourished and had fallen long before our time. And never since we had encountered a Reesan Key or heard of anyone else finding it. Perhaps you will be more lucky.

**Comment by tzerrell** [comment]
I keep going back and forth on whether this is ridiculous and awesome or ridiculous and too silly for Stellaris. I really like it ... I'm interested in additional opinions on the tone.

**Comment by Tuttu** [comment]
Well... I shouldn't have read it because now, I'm just like you and I don't know what to say. But I tend toward the "ridiculous and awesome" side. I think it could be a fun addition and if we think it's too much silly, we just lower the chance of appearance so it's used more like some kind of joke.

**Comment by Elimdur** [comment]
It is ridiculous and awesome and with a few little adjustments it will get serious enough to atleast reach the "russels teapot" anomaly amount of seriousness.

Also an idea for the end of the quest: Turn the colony into gaia. With all the nutrious soil it should become a garden eden :)

**Comment by ViolentBeetle** [comment]
Gaia seems a bit excessive, but not too excessive.

And I don't think what I've written is that much siller than usual Paradox fare.

**Comment by ViolentBeetle** [comment]
The text is done, the chain works. Needs ship models.

**Comment by Tuttu** [comment]
Good job. Have you been able to add the Curtator option as well?

**Comment by ViolentBeetle** [comment]
No, I don't know how to even approach the problem. From what I saw in how conversations are handled, adding new option to old screens seems impossible.

**Comment by ViolentBeetle** [comment]
One thing I might need help with is figuring out fleet:

- How to make it hold position in planet's orbit and return after combat
- How to allow everyone to see its name and names of its ships

**Comment by ExodusGaming** [comment]
I seriously just encountered this on my playthrough. you are a monster lol
