### ISSUE TITLE
Anomaly: Pioneer

### ISSUE THREAD

**Issue by ViolentBeetle** [MoreEventsMod/More_Events_Mod_Beta#238]
A small anomaly idea. Would appreciate help with xenophobe and xenophile flavour confirmation buttons. Possibly L2 or L3. Should trigger remnant story event.

Triggered on a star.

**Possible Small Craft**
Sensors indicate presence of a small artificial object orbiting [star]. 

**Success: Extrasolar Probe**
[Scientist] reports of successful recovery of the object. On examination, it appears to be a weathered primitive craft designed for unmanned travel between stars. Likely, it was launched millennia ago and travelled through multiple systems at sublight speed until it was caught into [Star]'s gravity. 

A plaque is mounted on the craft's hull, depicting several odd geometrical shapes, a scheme of an unidentified star system and a pictogram of two nude members of a species unknown to us. Why would any civilization see fit to disseminate such information throughout the universe is unclear.

>Gain Society research.

**Failure**
[Scientist] regrets to inform that [he/she] was unable to locate and recover the object. Whatever it might be, it is likely now lost forever.

**Comment by Chhkt** [comment]
On Success:
[xenophile/fanatic] "They obviously want to be found!"
[xenophobe/fanatic] "Then that's where we aren't going." or "They can keep their filthy nudity to themselves."

Just ideas.

**Comment by ViolentBeetle** [comment]
After long deliberation, I approve of
> [xenophile/fanatic] "They obviously want to be found!"

For xenophobe I myself partial to
> What a bunch of degenerates

**Comment by Rahorus** [comment]
finished with coding, needs testing and revision.

**Comment by ViolentBeetle** [comment]
It is long since implemented
