### ISSUE TITLE
Anomaly (Star) Solar Riches

### ISSUE THREAD

**Issue by Chhkt** [MoreEventsMod/More_Events_Mod_Beta#241]
Author: Chhkt
L2 Anomaly: Solar Riches
Image: GFX_evt_star_yellow

Can spawn on any star EXCEPT black hole and pulsar.

Initial Text: 
Scans of this star indicate that there may be a series of small structures stuck in a slowly decaying orbit.

Success 70%:
(scientist name) has found a number of decrepit solar collectors built by an unknown alien race. Even in their bad shape, they still continue to collect solar energy with greater efficiency than we have been able to manage ourselves.

Dialogue Choices:
"Take what we can" (+300 energy credits)

"Study their construction." ( if Applied Superconductivity is not already researched +20% progress Applied Superconductivity, else some research points)

Failure 30%:
(scientist name) reports that all traces of the structures have disappeared and apologizes for having miscalculated their orbital decay.

Dialogue Choices:
"Unfortunate."

**Comment by Kingtrin** [comment]
a branch has been created off dev called solar_riches. testing it now.

**Comment by Kingtrin** [comment]
the anomaly is largely finished but I left out the reward for a repeatable tech to avoid issues with has_technology. I substituted it for 20% progress to tech 2 power plants, if already researched then 20% progress to tech 3 power plants, if already researched then it gives research points. The first two options also give 10% progress to power hubs if not researched already. hope thats good enough. ^.^

**Comment by ViolentBeetle** [comment]
This anomaly is definitely done
