### ISSUE TITLE
Star anomaly: Neither Here Nor There - need outcome suggestions

### ISSUE THREAD

**Issue by ViolentBeetle** [MoreEventsMod/More_Events_Mod_Beta#243]
A difficult star anomaly, probably L4 or L5. Triggerable on any star.

**Abnormally cold star**
This star's energy output is noticeably lower than projected based on its spectral class and mass. It's as if a notable fraction of its energy is being drained elsewhere.

**Success: Neither Here Nor There**
The [Science Ship] has detected spatial disturbances around [Star] indicating a massive time-space rift is being formed around it. [ScienceOfficer] believes that some unknown entity has latched onto the star in order to use its mass and energy to create an exit rift for a very long-distance travel. Apparently, the rift has failed to form correctly, but it should be possible to manipulate it from our side.

Issue two mutually exclusive science ship special projects: Stabilize the rift and Collapse the rift. Input for what can come out of it would be appreciated.

**On successfully collapsing the rift**
A well-timed energy pulse sent in phase inverse to the rift's own vibrations had successfully neutralized it. Star's output had returned to normal and [Science Officer] reports that all spatial disturbances had seized. Whatever was trying to enter our galaxy has ceased to do so. Surplus energy released from the collapse will be a boon for our economy, while the observation of this rift has significantly advanced our understanding of time-space manipulation.

>Nothing comes out of rift and player received physics and energy.

**Failure**
The star´s energy output has returned to normal. Whatever was causing the drain has apparently ceased continuing to do so, leaving no trace that could provide us insight into its nature.

**Critical Failure**
While observing [Star], [Science officer] has reported detecting a massive energy wave, while our long-range sensors observed the formation of a massive energy rift that collapsed only moments later. Contact with the [Science Ship] was completely cut off and no debris could be found suggesting it was either completely vaporized or transported outside of our galaxy, if so likely with no means of returning.

**Comment by Elimdur** [comment]
For opening the rift lets spawn a big bad monster.

For this we´d just have to make the anomaly a one time thing globally and only let it spawn for non ai players.

The monster then could provide valuable research, like tech option for a very rare tech. Like letting you explore jump drives early. But you´d have to beat the monster first of course.

**Comment by ViolentBeetle** [comment]
I was thinking about slipping a fully functional ringworld that houses an entire powerful empire with all the cool stuff, but I'm not sure if it's feasible/a good idea.

**Comment by Elimdur** [comment]
this might be a bit over the top for a mere anomaly

But it would be entirely possible for a bitter event.

**Comment by ViolentBeetle** [comment]
This issue had eventually evolved into Broken Clock and is no longer relevant
