### ISSUE TITLE
Star anomaly: Flight recorder

### ISSUE THREAD

**Issue by ViolentBeetle** [MoreEventsMod/More_Events_Mod_Beta#246]
Easy star anomaly, L1 or L2.

**Initial**
We are picking up a repeating signal originating from orbit around [Star], presumably a distress signal or locator beacon.

**Success: Flight Recorder**
[Science Ship] has successfully intercepted and recovered a small device orbiting [Star]. Judging by the extracted data, it's a flight recorder from a military cruiser, jettisoned right before the ship was plunged into the star by either freedom fighters or nationalist fanatics who hijacked it in order to either fight imperialist oppression of their species or disrupt fragile galactic peace soon after their own star nation was either brutally subjugated by its treacherous neighbours or had its unjustified military aggression contained. Either way, the raw stream of flight data could be useful in research of our own.

Reward: Engineering points

**Failure**
[Science Ship] was not able isolate and track the signal again. Its source is likely lost forever.

**Critical Failure**
Soon after they picked up a small device orbiting [Star] we lost contact with the [Science Ship]. It appears the object was rigged to explode when brought aboard a spacecraft, likely as some sort of booby trap.

**Comment by tzerrell** [comment]
I've done minor proofreading edits in the main issue for English style. I also think the long sentence in the success event comes across as rather clunky, so I'm suggesting the following revision below (this is a big enough change I didn't want to do it inline and destroy your earlier work):

[Science Ship] has successfully intercepted and recovered a small device orbiting [Star]. Judging by the extracted data, it's a flight recorder from a military cruiser, jettisoned right before the ship was driven straight into the star by armed raiders. Depending on which set of voices we listen to on the interior cabin recordings, these hijackers were either freedom fighters or nationalist fanatics. The defending crew describes the intruders as terrorists who seek to disrupt the fragile galactic peace in a cruel retaliation for having their nation's wanton aggression contained; the boarding party presents themselves as liberators who are willing to give their lives to free their people from the yoke of imperialist oppression that has been forced upon them by treacherous neighbours. Either way, the raw stream of flight data could be useful in research of our own.

**Comment by ViolentBeetle** [comment]
The clunky long sentence was supposed to be the point, but if the point isn't worth it, we can go with your version.

**Comment by Elimdur** [comment]
What is the point in making it sound clunky? I was not sure at first if you were not sure in which direction you wanted to write it. It first made sense to me, when i read lamils version. 
The story though is good.

**Comment by ViolentBeetle** [comment]
The point I was trying to make is that scientists don't know the real story so report crammed both versions into a single sentence. @tzerrell got the point right, but I feel like he made it too elaborate for its own good. 

If people prefer the more elaborate version better, so be it.

**Comment by Elimdur** [comment]
It is good that he understood what you meant, because i did not. The way he has put it is much easier to understand for the reader and reads more fluently.

**Comment by BLimmie** [comment]
Coding done. Files in star_anomaly branch
