### ISSUE TITLE
Orila Event Ship Integration

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#247]
The ship in the Orilla quest has been having some issues. Specifically, we may need to (temporarily?) change the titan laser to a different weapon, as the locators for the windup effect also throw nonstop errors if you use it ingame.

I don't know how this is working in testing -- is it still a problem?

**Comment by Elimdur** [comment]
It might throw errors but is not game breaking in any way.

We plan to change the reward ship as a whole, complete with new weapons and so on before the next release.

**Comment by Elimdur** [comment]
reward ship integration done, thanks to frogs hard work
