### ISSUE TITLE
Star anomaly: Colours of another world

### ISSUE THREAD

**Issue by ViolentBeetle** [MoreEventsMod/More_Events_Mod_Beta#252]
L1 anomaly for the star

**Initial**
Observation of the star revealed flashes of unusual colours in its photosphere. Their spectral analysis does not match typical elements found inside stars of this class.

**On success**
Continued observation of the [Star]'s photosphere revealed multiple microwormholes linked to a different dimension. Their constant spontaneous formation and collapse inside the star is depositing large quantities of exotic particles within it, accounting for unusual spectral readings.
>Fascinating [+4 science on the star]

**On failure**
Initial observation of the star could not be replicated. It appears that the unusual readings were nothing more but a result of improper scanner calibration.

**Comment by tzerrell** [comment]
Updated for English style (it was just a few words/phrases that sounded like synonyms of the best word/phrase rather than the actual best word/phrase; no substantial changes)

**Comment by BLimmie** [comment]
Star anomaly branch.

**Comment by ViolentBeetle** [comment]
Did you fully complete it? What now?
