### ISSUE TITLE
Star Anomaly: Premature ageing

### ISSUE THREAD

**Issue by ViolentBeetle** [MoreEventsMod/More_Events_Mod_Beta#255]
L4 anomaly for main sequence stars. 

**Initial**
[Star]'s mass, energy output and spectral patterns lie outside the usual parameters for stars of its class and maturity, indicating accelerated ageing. 

**Success: Solar Extinguisher**
Long dormant energy traces in subspace and breaching points near the star's corona suggest [Star]'s rapid ageing was artificially induced. It appears that millions of years ago an energy beam from a distant system was launched at the star using technology far beyond our current understanding. A weapon, or perhaps as an exercise in cosmic-scale civil engineering, it ripped through the star's core, upsetting fusion processes inside it in attempt to cause the star to go supernova. Fortunately (or, perhaps, unfortunately) it failed to fully achieve its destructive goal, but anyone present here in two billion years will be able to fully appreciate the effect.

>[Default confirmation] It's a shame we can't trace weapon's origin point [Gain Physics]

>[Alternative confirmation with 5% (15% for materialists, 20% for fanatic materialists) chance to spawn instead] We should be able to trace weapon's origin point [Gain Physics, go to extra chain below]

**Failure**
The star is, without a doubt, ageing faster than we anticipated and is projected to go supernova in less than two billion years - at least two billion years too soon. However, we could not determine the cause of this anomaly.

**Extra chain**
If the player was lucky enough to get the alternative path, he gets a physics project for L5 scientist to trace back the solar extinguisher.

"Powerful weapon ripped through time-space continuum and transported enormous amount of energy at faster-than-light speed. Even millions of years later, the subspace breach points are lingering near the star and with some skill we should be able to trace their origin point."

**Upon completion:**
We're in luck! Methods that are normally useless in tracing usual subspace activity have proven to be useful for this particular occasion due to enormous amount of energy that was passing through once. We had pinpointed origin point of this energy transfer to a remote system.

Add marker to the situation log for a distant system. System needs to contain asteroids.

**Entering the system**
Get event:

"We were able to locate residue breach point near the system's asteroid belt. If we didn't know what to look for, we wouldn't even notice it, but now it might be just the place to look for the solar extinguisher we are trying to find."

Spawn L5 project for scientist to examine the asteroid.

**Upon scan**
For the uninitiated, it might look like just an ordinary space rock. But we know better. With our scanners uniquely calibrated we can see that this asteroid was once a part of an extremely advanced power transference system. What seems like simple metal deposits to others, is actually advanced circuitry that was once running within some planet's crust. It appears first use of the extremely powerful weapon was its last - massive energy overload tore the planet housing it apart turning it into an asteroid belt we know now. The ancient technology hidden inside is millennia ahead of us, but even in this state, mapping out power distribution circuitry is offering us an invaluable insight into energy weapon technology.

>Complete the chain. Gain "Solar Extinguisher technology" empire modifier, +5% energy weapon damage.

**Comment by tzerrell** [comment]
Completed minor English revisions.

**Comment by ViolentBeetle** [comment]
I've added "Extra chain" to the anomaly, it needs an editor too

**Comment by Tuttu** [comment]
There's something missing here : 
Upon completion:
We're in luck! Methods that are normally useless in tracing usual subspace activity have proven to be useful for this particular occasion due to enormous amount of energy that was passing through once. We had pinpointed ????

Add marker to the situation log for a distant system. System needs to contain asteroids.

**Comment by Tuttu** [comment]
There's something missing here :
**Upon completion:**
We're in luck! Methods that are normally useless in tracing usual subspace activity have proven to be useful for this particular occasion due to enormous amount of energy that was passing through once. *We had pinpointed ????**

Add marker to the situation log for a distant system. System needs to contain asteroids.

**Comment by Tuttu** [comment]
There's something missing here :
**Upon completion:**
We're in luck! Methods that are normally useless in tracing usual subspace activity have proven to be useful for this particular occasion due to enormous amount of energy that was passing through once. **We had pinpointed ????**

Add marker to the situation log for a distant system. System needs to contain asteroids.

**Comment by ViolentBeetle** [comment]
Fixed.

**Comment by Tuttu** [comment]
If you find the time to do it, could you come with title for each of the windows please ? 
**Premature Ageing** for the anomaly discovery and **Solar Extinguisher** for the success are pretty obvious but for the rest, I have no clue what you would have wanted.

**Comment by ViolentBeetle** [comment]
For project "trace the solar extinguisher" and "examine the asteroid"
POI: "Star extinguisher origin point"
For the final event, I think simply "The solar extinguisher"

**Comment by Tuttu** [comment]
Do you think you could come with a little description for the modifier ? Can't get a good one out of my mind.

**Comment by ViolentBeetle** [comment]
I don't think empire modifiers actually have descriptions.

**Comment by Tuttu** [comment]
When I was looking for examples, the Cloudbuster modifier add one. But it might not be displayed. I will check at home?
