### ISSUE TITLE
Demon Ship has no failure title

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#26]
There's no title for the event that spawns when your science ship fails to scan the initial anomaly of the Demon Ship event chain.

**Comment by Tuttu** [comment]
How can I get this issue assigned to me ? Only Mourn can do it ? 
I'm asking this because I will make a pass on this event today. :)

**Comment by tzerrell** [comment]
Hmm. I don't know :/ We will definitely want to sort that out. I made some minor text corrections when I was looking at this event chain, which you may want: https://github.com/tcarrell/More_Events_Mod_Beta/tree/demonshipedits

This is the branch I tested out making event flowcharts on, so I have one which you may or may not find helpful: https://drive.google.com/file/d/0BwDuqTBhjNwxQU5NczJ2OWczTkk/view?usp=sharing

**Comment by Tuttu** [comment]
Thanks for all of that. I wasn't aware you had work on this. If you want to continue, I can give you the list of changes that have to be done.  :)

**Comment by tzerrell** [comment]
Closing issue as it should be fixed by pull request #28
