### ISSUE TITLE
Anomaly: Magma fortress

### ISSUE THREAD

**Issue by ViolentBeetle** [MoreEventsMod/More_Events_Mod_Beta#265]
An molten world anomaly. Should be about L3

**Initial**
Deep scans indicate an unusual shape on the surface, indicating a possible artificial structure.

**A Strange Structure**
Deep penetrating scans revealed a small outpost on the planet's surface partially submerged in magma and covered in volcanic ash. We should be able to learn more by dispatching a skilled science team.

>Start preparing an expedition
>Spawns level 4 engineering project to go investigate the outpost.

**Alien Fortress**
Our archaeology team had successfully used heat-resistant equipment to dig deep into the alien outpost. They had found multiple remains of short, strudily-built mammalians. From images on the walls, floors and everyday objects the entire history was easy to reconstruct. The facility was established in this harsh conditions under the belief that that deep underneath they could find a vein or two of a rare and incredibly valuable ore and used their unique methods of pumping magma to the surface as an all-purpose energy source, defence system and a mean to dispose of undesirables. At first, outpost had grew and its prosperity had attracted many newcomers. Many had turned to fine arts, creating objects intricately decorated with fractal images of themselves and other weird and beautiful creations. Despite being constantly besieged by rivals, the colony endured for a few generations, but as the dig to the planetary core drew near conclusion, it met its doom from inside. Resource mismanagement had resulted in shortage of intoxicants and clothing, complicated with inhabitants short temper had driven fortress into full-scale riot and vandalism spree, with more and more inhabitants losing their temper and joining the riot. Combination of inter-personal violence and operation disruption ultimately drew the facility to extinction.

>[Generic] Quite a story of greed and intemperance [Gain society research]
>[Xenophile] Such a unique and amazing species [Gain society research]
>[Xenophobe] Truly, all xenos are mad [Gain influence]

**Failure**
It seems the strange shape was just a plateau with heat and uneven density of magma distorting the results. Nothing artificial is found at the site.

**Comment by Elimdur** [comment]
An molten world anomaly. Should be about L3

Initial
Deep scans indicate an unusual shape on the surface, indicating a possible artificial structure.

A Strange Structure
Deep penetrating scans reveal a small outpost on the planet's surface partially submerged in magma and covered in volcanic ash. We should be able to learn more by sending a small expeditionary team down there.

    Start preparing an expedition
    Spawns level 4 engineering project to go investigate the outpost.

Lava Fortress
Our archaeology team successfully used heat-resistant equipment to dig deep into the alien outpost. They found multiple remains of short, strudily-built aliens of apparently mammalian origin. From reliefs on walls, floors and everyday objects a big part of their history could be reconstructed. The facility was established in this harsh conditions under the belief that that deep underneath they could find a vein or two of a rare - and to them incredibly valuable - ore.\n\nBy pumping magma to the surface they were able to access a nearly inexhaustible energy source, build a defence system relying on multiple lava floodable areas, as well as findind a means to dispose of "undesirables" - as shown on an extensive amount of reliefs.\n\nAt first, the outpost had grown steadily and its prosperity had attracted many newcomers. Many inhabitants did not only work in the mines but had also turned to fine arts, creating objects intricately decorated with fractal images of themselves and other weird yet beautiful creations.\n\nDespite being constantly besieged by nebulous rivals, the colony endured for multiple generations. But as the dig to the planetary core drew near conclusion, a catastrophic event from inside the community must have happened. Judging from their statable injuries and as there are only remains of this one alien species the implication of a devastating civil war arises. As their storage was filled which all kinds of goods and equipment our science team doubts that a ressouce shortage could have been the cause of the crisis. Though to the amusement of the others one of our scientists pointed out there wasn't any kind of protective foot gear despite the fact that most of the reliefs found empasize it as a sign of social standing. Unfortunately our team was unable to find out any more details.

    [Generic] Quite a story of greed and intemperance [Gain society research]
    [Xenophile] Such a unique and amazing species [Gain society research]
    [Xenophobe] Truly, all xenos are mad [Gain influence]

Failure
It seems the strange shape was just a plateau with heat and uneven density of magma distorting the scanning results. Nothing artificial was found at the site.

**Comment by ViolentBeetle** [comment]
**Critical failures**
The research team had successfully located an abandoned complex on planet's surface. However, when exploring its vestibule, [Science officer] appears to have stepped on a pressure plate of a sort, somehow causing the a stream of lava from outside to pour from the ceiling and fill the entire facility. Both the complex and our science team are lost.

The strange shape turned out to be an alien outpost of a sort. However, after choosing to explore the interiors, [Science officer] unwittingly pulled a lever seated in one of the rooms, causing the apparently sole support column to suddenly snap, causing the cave-in and total destruction of the entire complex.

**Danger room fail**
Our archaeology team successfully used heat-resistant equipment to dig deep into the alien outpost. They found multiple remains of short, strudily-built aliens of apparently mammalian origin. Looking further into the complex [Science officer] wandered into what [he/she] believed to be some kind of gymnasium. Unwittingly activating a lever in the room caused multiple spikes to quckly emerge and retract from the floor, apparently set to train users in dodging techniques. By the look of it, [Science Officer] and most of his team were mediocre dodgers at best.

>This complex is a death trap! We should seal it off [Gain unfluence, scientist dies]
>We should start assembling a second team
The second option enables a second anomaly. 

**Success**
The event is mostly the same, except the beginning is different.

Using tunnels already dug by their predecessors and armed with a warning to not fiddle with lever, our second science team had made its way into the complex.

**Failure**
The second science team had successfully entered the complex. Despite their best efforts to not pull any dangerous levers, [Science officer] apparently unwittingly stepped onto a pressure plate of a sort, somehow causing the a stream of lava from outside to pour from the ceiling and fill the entire facility. Both the complex and our science team are lost.
>The only winning move is to not play

**Comment by Elimdur** [comment]
Test with add_anomaly mem_lava_fortress_category

Note that "Loosing is FUN" If you fail the anomaly you have a big chance of getting a specific event setting a new anomaly to "try again"
