### ISSUE TITLE
His Her, Him Her , He She in localisation

### ISSUE THREAD

**Issue by Elimdur** [MoreEventsMod/More_Events_Mod_Beta#268]
[officer.GetHerHisCaps]
[officer.GetHisHer]
[officer.GetHerHis]
[officer.GetSheHeCaps]
[officer.GetSheHe]
[officer.GetHimHer]

We should go through our texts and get rid of all these awkward "they"s when we find the time.

**Comment by Elimdur** [comment]
Reworked the demon ship event to include these.

**Comment by Mariawr** [comment]
I would like to note using "they" isn't nearly as awkward as it might seem in English. It's the go-to word for addressing a person with unknown gender (and not some insanity tumblr cooked up) and people don't exactly raise an eyebrow reading the word.

**Comment by ViolentBeetle** [comment]
So, if the focus is ship, we should actually use "Leader" instead of "officer". Just a reminder in case I try to code again and forget this.

**Comment by ViolentBeetle** [comment]
I think we cleared everything we remembered to clear long ago. No need to keep clutter. We know now.
