### ISSUE TITLE
1.9 Proofreading Check

### ISSUE THREAD

**Issue by Elimdur** [MoreEventsMod/More_Events_Mod_Beta#273]
- [x] Ancient Factory Anomaly
- [x] Abandoned Mecha Anomaly
- [x] Accelerated Evolution Colony Event
- [x] Flight Recorder Anomaly (in dev)
- [x] Crystal Pyramid Anomaly
- [x] Ancient Robots (Colony Event) (in dev)
- [x] Sleepers Observation Post Event
- [x] Stellar Cloud Anomaly (in dev branch)
- [x] Lava Fortress Anomaly  (in dev)
- [x] Hollow Asteroid Anomaly (the small anomalies + pirate quest)  (in dev)
- [x] Lunar Gate Colony Event
- [x] Solar Riches Anomaly (in dev)
- [x] Star Colors (in dev)

Please add more, if I have missed some

**Comment by tzerrell** [comment]
What's "flight recorder anomaly"? I don't see it in `dev` and I also don't see a branch with that name

**Comment by BLimmie** [comment]
Ignore that. It's in the star anomaly branch, and I'm planning to merge all of the star anomalies together once I have time after finals.

**Comment by tzerrell** [comment]
On the sleepers major dialogue window (`mem_sleepers.150`) the \n\n\n\n\n\n\n\n workaround isn't working -- if you aren't scrolled down all the way to the bottom (which plenty of people won't be) you don't see any dialogue in response. However, if you are scrolled to the bottom, you need the workaround to see the response.

I propose splitting this into a standard text event giving the circumstances of their awakening, followed by a pure-dialogue diplo event where the text doesn't overflow.

**Comment by tzerrell** [comment]
sleepers split finished, find it in `english_proofreading`

**Comment by tzerrell** [comment]
I've marked hollow asteroid as complete, but there is the outstanding question of what to do with the following:
``` 
 mem_hollow_asteroid.103.a:0 "A job well done."
 mem_hollow_asteroid.103.b:0 "A job well done."
```

**Comment by ThePrettiestIncubus** [comment]
I've done a readthrough of the Satellite Cloud eventchain, and everything was mostly in order. I just made some minor changes for flow. To make it sound more natural to english speaker.
