### ISSUE TITLE
Event chain: Death World

### ISSUE THREAD

**Issue by ViolentBeetle** [MoreEventsMod/More_Events_Mod_Beta#274]
Event can be triggered on any Gaia world that isn't a holy world or reserved for something else.

In order to trigger, it needs to be colonized for at least 10 years and have at least 3 pops.

**Phase 1: Dangerous awakening**
Previously benign ecosystem on [Planet] seems to be undergoing rapid change. Multiple previously docile native creatures are becoming more hostile to our colonists and attacking. Dozens reports of injuries overnight accompany the sudden rise of aggression and threaten to overwhelm planetary healthcare system if the trend continues.

>Worrying
>Add "Dangerous native life" modifier [-10% habitability]

While under the effect, following events might trigger repeatedly

**Ransacked storage**
Large number of small native rodents have somehow found its way into one of the planetary storage facilities on [Planet]. Despite their small size, they have caused considerable damage to sensitive equipment stored there, many items need to be replaced as soon as possible

>Unfortunate [Lose 100 minerals]

**Civilian injuries**
Citizens on [Planet] were warned to remain indoor, but this time it wasn't enough. A habitat block was infiltrated by venomous creatures who emerged from ventilation shafts stinging residents. Despite lack of fatalities, citizens are quite distressed by the event and some of the victims might have to spend a significant time recovering

>Nasty vermin [Planet gets -10% happiness for 6 months]

**Plague of insects**
Large number of large insects had emerged from the ground planet wide. Although hardly dangerous on their own, large numbers of them threaten to disrupt infrastructure on the planet, with their hard carapaces clogging the utilities and engines of planetside vehicles.

>Disgusting bugs [Planet gets "insect plague" modifier -10% of all outputs]

**Phase 2: Wildlife agression grows**
We are getting the first reports from [Planet] of local wildlife actively hunting and killing colonists. The casualty rate is low, but it grows, and the trend can not be ignored. The native organisms show rapid change in phenotypes as they adapt to our tactics and methods faster than any evolutionary model could predict. 

>Something has to be done [Planet gets "Hostile native life" modifier: -15% habitability -20% minerals and energy +30% building cost -75% migrant attraction]

In addition to phase 1 events, following events might randomly trigger

**Survivalist militia**
Concerned about their future on the planet, many colonists have chosen to dedicate their time to study weapons and wildlife survival techniques in case native life keeps its offensive. The survivalist movement is gaining new members with every day.

>Support the initiative [Costs 250 minerals. Planet gets "survivalist militia" modifier +5% habitability -10% minerals and energy output, armies built on the planet has +10% hp]
>Allow the initiative [Planet gets "survivalist movement" +5% habitability -5% minerals and energy]
>Discourage the initiative [Planet gets no modifier, but -10% hapiness to all pops for a year]

Everyone on the planet also becomes fanatic militarist or just militarist

**Death swarm**
Today large swarm of unusually violent beetles had descended from the skies of [Planet]. Before authorities could react, multiple civilian workers were bitten many times and soon succumbed to deadly venom.

>This is a disaster [One pop is killed. -20% hapiness for a year]

**Stampede**
Multiple large previously docile mammals had amassed today and attacked one of facilities on [Planet]. They had rammed its walls multiple time with their hammer-shaped heads until the sheer strain had caused a collapse. The creatures then trampled the ruins so more before fleeing into the wilderness. At least workers were able to flee and civilian casualties were kept to minimum.

>They need to be stopped [Random building is ruined -5% hapiness to all]

**Phase 3: Nature's revenge**
The native life on [Planet] grows more aggressive and organized with every day. They are able to execute complex manoeuvres and evade our forces. The planet is now borderline death world, where simple everyday survival is a monumental task.

>We need to find a way to stop it before its too late [Planet gets "Nature's revenge" modifier -30% to habitability and hapiness -50% to all outputs but food and society -100% migrant attraction]

**Purity movement**
The colonists on [Planet] had enough traumatic experience with alien life to turn them extremely distrustful to all that is not like them. The xenophobic movement is on the rise.

>[Xenophobe] They know what's good for them
>Worrying
Pops are becoming xenophobe and fanatic xenophobe

**Looking for a solution**
This chain starts soon after phase 2

The ongoing situation on [Planet] has prompted many experts to propose the solution to the crisis. As the wildlife aggression grows, the need to do something is clear. We only need to choose what.

>[Not fanatic xenophile or fanatic pacifist]We must look into ways to destroy the aggressors [Progress into War on Nature]
>[Not fanatic xenophobe]We must study the wildlife more closely [Progress into Studying the Nature]
>We should find a way to bunker down and hope for the best [Progress into Walled Garden]
>[Needs Psionic theory]The force behind the wildlife aggression must be psionic. We could tap in it [Progress towards Battle of Wills]

**War on Nature**

Spawn a long society five star project to observe the wildlife behavior from orbit. On success:

Extensive research into the hostile ecosystem on [Planet] had revealed several vulnerable points that would disrupt the whole if struck. Military commanders propose two possible solutions - by deploying a specific weapon from safe orbit, tailored to destroy the wildlife, they could execute the plan safely but collateral damage would be enormous. Ground operation has less chance of success and would likely require off-world reinforcements, but should keep the planet's gaia potential intact.

>Let's destroy them from orbit. It's the only way to be sure [Go to Wildlife removal]
>Boots on the ground solution is preferable [Go to Extermination or Bust]

**Wildlife removal**
5 star society project

Our scientists had developed a specific weapon tailored to handle the wildlife on [Planet]. Combining biological agents and conventional weapon, they should force entire ecosystem to collapse.

On success:
Our predictions were true. When struck with our advanced weapon, the entire hostile econsystem has collapsed. However, the solution was not without side-effects. Massive sudden destruction of entire planet's overgrown ecosystem had released energy forcing climate change and turning the world into a wasteland

>At least it's our wasteland [End chain. Planet turns into tomb world. It has "Biomass wasteland" modifier that gives it +30% society output]

**Extermination of Bust**
A 1 day project with no requirements:

Our analysts have compiled a list of weak points where our troops can strike, disrupting the entire ecosystem. However those areas are protected by strong, organized wildlife resistance and we can expect full scale retaliation when we attempt an attack. We need to make sure our troops stationed on planet is up to the task before we launch an attack.

When project is activated, monster armies in spirit of titanic wildlife spawn. 

**Our forces victorious**
As analysts anticipated, multiple strikes at weak points had disrupted the ecosystem enough to cause a massive collapse. Almost all niches had been disrupted and starved and disoriented creatures are making easy target for our mop-up operations. 

>We have taken the planet back [Planet remains Gaia and gets "Wildlife graveyard" modifier +20% society]

**Our forces lost**
We had anticipated the resistance from wildlife, but we did not anticipate this. Our own forces were routed and exterminated. Seemingly spurred by our aggression, the ecosystem rapidly changed towards exhaling toxic gases into the atmosphere, quickly and hostilely changing its composition and turning it uninhabitable. 

>The planet is lost [Planet becomes a toxic world. It has "Death world" modifer that gives it +9 society research]

**Studying the nature**
Spawn "Study wildlife" society project for level 5 scientist. 

On completion:
Extensive sampling and autopsy of hostile wildlife on [Planet] had proven to be quite valuable in understanding its nature. Despite being separate and genetically distinct species, all appear to have foreign material stuck in their tissues, somehow bonding them together. Constant immune suppression prevents the host's antibodies from targeting it. Understanding this effect has opened our eyes to possible ways to solve our problems?

>[Not xenophobe] What if we use the tissue to help our colonists be in peace with the planet? [Go to In Harmony With Nature path]
>[Not xenophile] What if we find a way to disrupt the immune suppression? [Go to Immune Suicide path]

**In Harmony with Nature**
Spawn society special project to adapt to planet's hostile ecosystem. On completion:

The first test subjects had shown amazing potential to control and direct the strange tissue that bond together the wildlife on this planet. They were able to avoid being attacked by the native species. Soon enough, safe and easy tissue implants were distributed among the population.

The tissue had been not without side effects. The subjects find it hard to operate off-world, but it's a small price to pay for control of the planet. The newly formed symbiosis had accelerated the wildlife spread, turning the planet into a strange new world hostile to all but few who let the bond tissue inside them.

>Fascinating
The planet gets unique type "Death world" with zero habitability for all. Its population however gets "Death world adaptation" which gives 100% death world habitability and nothing else. The planet gets "Harmonious life" modifier that gives +25% to all outputs.

**Immune suicide**
Spawn society special project to cause mass rejection of bond tissue. On completion.

A small but effective strand of viral agent - one thing that native life of [Planet] could not adapt to. A pandemic spreading across the native creatures populations causing fatal rejection chain reaction in their organisms. Soon enough, all the dangerous creatures have died out.

>Perfect  [Planet remains Gaia and gets "Wildlife graveyard" modifier +20% society]

**Walled Garden**
Spawn engineering special project to create planetary fortification:

Our engineers had laid out a plan to protect colonists' habitats from growing dangers and pacify the native wildlife without having to openly confront them. A combination with earthquake simulating hammer installations, electromagnetic-based disruptors and sonic fences we should be able to deter any further activity in our areas.

The planet can now build "deterrence hub" that gives more planetary fortification and improves army building, but cost a lot of minerals.

**Walled Garden complete**
We have successfully deployed our defences. Although some areas are not viable to defend with it and had to be abandoned, the rest should be safe from further incursions. 

>Let there be peace in our time [All modifiers are removed. The deterrence hub can not be removed. Spawn 2-4 permanent blockers of "Nature's revenge" that give +2 society output on adjacent tiles]

**Battle of Wills**
Spawn society project to test wildlife for psionic activity

We were right! The wildlife does have a collective mind guiding it, facilitated by psionic activity. It seems that a growth deep beneath the surface is acting as a giant mind, guiding the planet's life through pieces of its flesh that infect them. This should allow us to communicate with... or destroy it by other means.

>Psionically link with the planetary mind [Go to Planetmind]
>[Not fanatic xenophile]Use the newfound knowledge to strike at the root of the problem [Go to Root of All Evil]

**Planetmind**
Spawn society research project. One of the two outcomes are possible.

**Success - Planetmind pacified**
Multiple psionic experts from our empire had travelled to [Planet] to engage with the mind that guides it. Their collective wills had wormed their way into psionic connection that runs through the planet's ecosystem. Overwhelmed by this mental attack, the planetmind was not able to resist and had been successfully pacificed, its bestial will rewritten to our ends.

>Good job [Planet gains "Planetmind" modifier that gives +25% to all sciences and +20% to food]

**Failure - Planetmind victorious**
Multiple psionic experts from our empire had travelled to [Planet] to engage with the mind that guides it. Their collective wills had wormed their way into psionic connection that runs through the planet's ecosystem. Unfortunately, the planetmind was stronger than they expected. Not only it destroyed their minds whole, it had learned from them how to attack colonists' minds directly. Soon most of the colony was under its control. Apparently worried of further attacks, it had changed biocycle of the life to produce atmosphere unsuitable for us and soon the colony was lost to us permanently.

>The planet is lost [Planet becomes a toxic world. It has "Death world" modifer that gives it +9 society research]

**Root of all Evil**
Spawn 5-star society project to locate and destroy the planetmind system. On success:

With planetmind structure mapped out by the psionic experts, our scientists were able to locate several major metabolic nodes, that power the whole system. With several tonnes of highly potent neurotoxin injected inside those nodes via a massive drilling platforms, we were able to watch in real time as the planetmind veins withered and died while life on the surface returned back to normal.

>Victory is ours! [Planet gets "Dead planetmind" modifier: +20% to society]
>[Xenophile a pacifist] Such tragic loss. But we had no choice.

**Failure to do finish the project it reasonable time**
The life on [Planet] had underwent a dramatic change. Its metabolism had been changed to exhale gases that are extremely toxic to colonists and corrosive to colonial equipment. The native ecosystem thrives while our own colonists have died or were forced to flee.

>The planet is lost [Planet becomes a toxic world. It has "Death world" modifer that gives it +9 society research]

**Comment by Elimdur** [comment]
Last time i tried, negative habitability modifiers didn´t work on gaia worlds, you´d have to go with negative happiness instead.

**Comment by ViolentBeetle** [comment]
Interesting. I guess hapiness penalty should be higher.

**Comment by CaligulaCaesar** [comment]
I've proofread this, but I haven't ticked it off as we need significant work to provide variations for hive minds, machines and synths. Specifically (off the top of my head):
-Every reference to individual initiative must be changed for hives and machines.
-For machines and synths, we would need to either disable the bit where you basically genetically alter yourself or rewrite and recode it to work for them (but then, they don't have habitability anyway I think, so that's tricky).
-I'm not sure atmospheric gases would make it permanently uninhabitable for machines and synths.
-Machines and hives have no happiness, so wouldn't care about that, a workaround could be to do negative income modifier due to work being disrupted.

I can work with you to implement this, if you want, it's a cool event.

**Comment by ViolentBeetle** [comment]
The version in files has a special hive mind branch and a blocker for some of the random events.

It was implemented before machines though.

**Comment by CaligulaCaesar** [comment]
Ah I missed that, I'll check through again, I can see it in the events file now.

I wouldn't be too hard to make it work for machines, it would just mean changing it to machine units being destroyed and stuff.

**Comment by ViolentBeetle** [comment]
I don't really have time right now, so if you feel like going through this branch, be my guest.

**Comment by ViolentBeetle** [comment]
Event is more or less finished, no need to keep this around.
