### ISSUE TITLE
Frozen world anomaly: Stuck in a glacier

### ISSUE THREAD

**Issue by ViolentBeetle** [MoreEventsMod/More_Events_Mod_Beta#278]
LV 2-3 anomaly for a frozen world

**Initial**
A small foreign object is detected within glacier on planet's surface. 

**Kinetic projectile**
Preliminary observation identified the object as a large kinetic artillery round, apparently shot at the planet in distant past. Evidently, some ship launched it from high orbit causing it to penetrate about 50 meters of ice before stopping. Technology that allowed it to survive the impact might be quite useful. 

>Find a way to recover the object [Spawn engineering project to recover the artillery round from glacier]
>We are not drilling glacier for a piece of junk [Get influence]

**Recovered: Worthless**
After the long and difficult dig, [Science officer] reports that the round was not of any value. All design solutions apparent we could possibly copy are already available to us.
>What a waste

**Recovered: Reinforced rounds**
[Science officer] had successfully recovered and examined the projectile. It appears to utilize some unusual layered composition that allowed it better penetration and increased impact energy. 
>Good work [First time: Gain +5% kinetic damage empire modifier. If happens again: +5% to kinetic damage repeatable tech]

**Recovered: High calibre**
(Can only be gotten if mega cannons are not researched)
Upon recovery and examination high calibre of a round becomes the most notable feature. It suggested certain solutions to weapon technology that might open us new possibilities of extra heavy weaponry.
>Good work [Unlock mega cannons technology]

**Robot**
It appears, a robotic unit of a sort was placed within glacier. Judging by scarring and refreezing patterns on the glacial surface, it was thrown from planet's high orbit and penetrated the glacier under the impact velocity and heat from re-entry through thin, but not non-existent atmosphere.

>We should recover it [Spawn engineering project to dig it out]
>[If empire had ban robotics] Let the abominable machine lie dead [Gain influence]

**Recovered: Damaged**
(Event is guaranteed to trigger if player has no robotics tech whatsoever, less likely to trigger with robots and droids tech. Synth tech prevents this from triggering at all)

[Sicence Officer] reports that [his/her] team's lack of familiarity with alien technology had caused irrepairable damage during recovery operation. The unit is now only good for scrap metal.

>Scrap metal it is [Gain some minerals]

**Recovered: Functional**
The recovered robot appears to be fully functional and highly sophisticated. Its personality matrix, with only a handful of adjustment, could be reprogrammed to serve our empire's needs.

>[If robots are legal] Bring it online
>[Gain a 5-star leader of 1 out 4 types: Governor named "Diplomatic" with "iron fist" trait. Scientist named "Understanding" with "maniacal" trait. Admiral named "Negotiator" with "agressive" trait. General named "Appeaser" with "butcher" trait] 

>Scrap it for components instead [Gain some minerals]

**Dead explorer**
The object sensors picked up initially turned out to be a sealed exo-suit with its occupant, member of a species unknown to us, still inside. Judging by the damage sustained by the suit, someone had repeatedly bashed the suit's visor with a large rock until its integrity was compromised, and after its user suffocated, threw the body into a crevasse. Both suit technology and corpse inside could be of major use for us.

>[Not xenophobe] At least someone could now tell their story
>[Xenophobe] Looks like the xeno will be of some use after all 
>[Gain society and engineering research]

**Crashed supply shuttle**
[Science officer] surprised to report that the object found on site, is one of our own supply shuttles. This particular shuttle had went off the grid a few months ago during a scheduled flight. Flight recorder in the cockpit contains a message from the pilot where he blames [Adjective] society's lack of appreciation for him and [Empire leader]'s name conspiracy to persecute him in particular as main reasons to steal and crash the shuttle.

>Tragic
>[Collectivist] What a waste of government's property
>Gain influence

**Meteorite**
The team sent on site had found a lump of meteorite iron inside the glacier. Judging by its composition, it might be extragalactic in origin, travelling for aeons until being caught in planet's gravity and eventually crashed on its surface, remaining shallowly burrowed for some more aeons.

>Such is the great journey of life [Gain small amounts of minerals]

**Data cache**
Apparently, someone had melted a spot in the glacier, before placing a small navigational computer inside and letting the water re-freeze. Whatever is hidden there might be of value.

>It could be useful [Spawn physics project to recover the computer and extract the data]

**Data extracted**
It seems some unknown space pirate had hidden this data here in case they ever need a bargaining chip. It contains a set of coordinates that should lead is to a hidden treasure.

>Let's see where it gets us [Spawn a project to find pirate treasure on barren planet nearby]

**Treasure: Nothing**
After following the coordinates, we had found a vault well-concealed on [Planet]'s surface. However, whatever was once hidden here was long since removed by someone else. The vault is empty.

>What a waste of time

**Treasure: Hidden valuables**
We have discovered a vault concealed on [Planet]'s surface. Vast deposit of valuable items had been recovered by our specialists.

>Excellent [Gain minerals and energy]

**Treasure: Hidden hangar**
The vault found by following mystery pirate's coordinates was not so much vault, as it was a hangar hiding a massive pirate ship. Its state-of-the-art equipment could be quite an asset to our military forces.

>Excellent [Gain pirate cruiser with good equipment, but not potential for upgrade]

**Failure**
The "object" detected within planet's glacier was revealed to be a simple boulder, stuck inside. Its unusual shape and composition produced abnormal readings, but is of no interest beyond that.

>Disappointing

**Comment by Tuttu** [comment]
Sounds like a fun little anomaly. However, I think we shouldn't offer the Mega-Cannon tech but only a small percentage of completion toward it because it seems a bit OP otherwhise.
I will go for it during my midday break as I usually don't have a lot of free time at this moment of the day so small anomalies / events like this one are great for that. :)

**Comment by ViolentBeetle** [comment]
Actually, I almost did it myself, learning various stuff, except for pirate treasure. I've commented out pirate treasure stuff because I couldn't understand process of star selection.

**Comment by Tuttu** [comment]
Damn. I will pick another one then. :D

**Comment by ViolentBeetle** [comment]
You can complete the data cache in the glacier branch. Because I just can't figure out how it works, yet. 

PS. I edited your comment that seemed to include your e-mail signature, in case you didn't mean everyone to see your real name.

**Comment by Tuttu** [comment]
Can you give me the branch name then ? I might get a look at it. :)
Also, thanks for the edit.

**Comment by ViolentBeetle** [comment]
It's called "glacier".

**Comment by ViolentBeetle** [comment]
Event is done, needs testing and proofreading

**Comment by ViolentBeetle** [comment]
And we done here. It's not in dev. Tested by me, seems to work fine.
