### ISSUE TITLE
Observation post event: A visitor

### ISSUE THREAD

**Issue by ViolentBeetle** [MoreEventsMod/More_Events_Mod_Beta#287]
A shot event chain that fires on observation posts. Extra outcomes could be useful.

# Impact event
Our observation post over [Planet] had picked a heat emission below that matches profile for atmospheric re-entry, followed by an impact on the surface. An asteroid small enough to slip past our sensors would burn up before hitting the ground and the fact that it didn't suggests that this might not be natural. The impact occurred right outside a populated area with casualty estimate low to none.

>[Xenophile] We should recover the object before it contaminates their civilization
>We should recover it for ourselves
>[Xenophobe] Savages should not be allowed to get this technology
Progress towards **Recovery**

>[Xenophile] What falls on their planet is their to keep
>We should leave it be
>[Xenophobe] Ignore the space garbage
Progress to **Natives have it**

>[Militarist] Sterilize the area before it causes any trouble
Progress to **Sterilization**

# Recovery: Object secured
Probability of this event increases the more primitive the civilization is

The covert team dispatched from the observation post successfully landed on the scene and recovered the object before the natives discovered it. With the small artificial object safely in their hands, they departed... hopefully unnoticed.

>Good job
Progress towards **Object is our**

# Recovery: Too late

The team dispatched from the observation post was too late. A group of natives had already made its way to the impact site and left with a small unidentified object. To recover it now would expose our personnel to additional danger, and our entire operation to exposure.

>We should steal it back
Progress to **Theft of the object**
>Fine, they can keep it
Progress to **Natives have it**

# Theft of the object: Failure

Despite the best efforts of the observation post personnel and recovery team, they have lost track of the object. We will have to wait for it to resurface at some point in the future.

>Most unfortunate
Progress to **Natives have it**

# Theft of the object: Success

Using satellite images our team successfully infiltrated the location where the natives who found the object camped for the night. Our agents successfully stole the object and were able to escape unnoticed.

>Good job
Progress towards **Object is our**

# Theft of object: Unfortunate incident
This event shares probability pool with two following, and becomes less likely with militarism and pacifism.

Our team successfully tracked down natives who found the object to a nearby settlement. However, during the attempt to covertly recover it, our agents were detected and attacked by the panicked primitives frightened by alien appearance. In ensuring fight most attackers were stunned and their memories wiped, however we can not be sure we have left no witnesses. The object, however, was successfully recovered.

>At least we got some results
Progress towards **Object is our**, low chance of planet going xenophobe or militarist

# Theft of object: Bloodbath
This event is more likely with militarism

Our team successfully tracked down natives who found the object to a nearby settlement. However, during the attempt to covertly recover it, our agents were discovered and attacked by the panicked primitives. A large number of attackers were killed in self-defense with the rest fleeing. It will be hard to contain the situation now with so many surviving witnesses and the clear evidence of carnage. The object, however, was successfully recovered.

>[Xenophile] Tragic
>Most unfortunate
>[Xenophobe] And nothing of value was lost
>At least we got some results
Progress towards **Object is our**, high chance of planet going xenophobe or militarist

# Theft of object: Disaster
This event is more likely to happen with pacifism

Our team successfully tracked down the natives who found the object to a nearby settlement. However, during the attempt to covertly recover it, our agents were discovered and attacked by the panicked primitives. Unwilling to harm their assailants, the extraction team attempted to flee, resulting in the death or injury of several of our agents, lost of the object and a potentially disastrous information leak.

>This is a disaster
>[Xenophobe] Was it really worth it?
Progress to **Natives have it**, medium chance of planet going militarist or xenophobe

# Sterilization

A shuttle deployed from our observation post launched a medium-yield missile from a high altitude at the object's impact site. After the dust settled, surveillance is no longer picking any foreign object on site and with any luck we should be able to pass this event as a second meteorite strike in the same spot.

>This can happen, right?
Gain 25 influence. There might be one follow-up or there might not be

# Sterilization: Religious development
Can always happen

Our actions on [Planet] were not unnoticed by the natives. Many took double detonation to be a divine sign and multiple places of worship popped up on the edges of the crater. Several religious cults based on the event are spreading across the planet.

>Interesting
Push natives to spiritualist

# Sterilization: Alien plot suspected
Needs to be industrial to happen

It seems authorities on [Planet] had identified our actions as alien incursion. Not having full picture, they are blaming the double detonation on an unknown alien force and consider major inventions into defence industry and military organization to repel the expected invasion.

>[Xenophile] What have we done!
>Worrying
Push planet to militarism, xenophobia or materialism

# Sterilization: Tension
Needs to be industrial

It doesn't seem that authorities on [Planet] suspect any extraterrestrial involvement, but they do not buy the meteorite strike version either. Accusations of development and testing of weapon of mass destruction are flying and international tension is higher than ever.

>[Xenophile] What have we done!
>Worrying
Push planet to militarism. If mechanics allow, increase chances of nuclear destruction (If it's atomic age)

# Natives have it: Lost and never found

It's been a while since the mysterious object made an impact on [Planet]'s surface and we didn't hear of it ever since. Our experts on the observation post firmly believe it was lost forever.

>Much noise about nothing
Chain simply ends.

# Natives have it: Prophet from the stars
Planet needs to be pre-industrial

It seems natives who recovered object are now revering it as some kind of divine messenger. We determined that the object is indeed speaking and possess a rudimentary AI, but its incoherent ramblings are impossible to decipher and fairly useless. What was its original purpose and where it came from remains a mystery.

>But its effect on society is very interesting
Push planet to spiritualism, gain society research and influence

# Natives have it: Alien menace
Planet needs to be industrial

The object that crashed recently on [Planet] resurfaced again on a big presentation by one of the planet's governments. On the gathering of top scientific experts and leaders of major nations, it was unveiled as a definitive proof of alien life. The speeches made on the assembly had noted danger that discovery points to and what measures need to be taken to defend from it. "This changes everything, - the speech noted, - and we got to be ready".

>Worrying
>[Xenophobe] It won't save them
Push planet to xenophobe, militarist or materialist ethic. Gain society and influence

# Natives have it: Alien teacher
Planet needs to be industrial

The object that crashed recently on [Planet] was revealed today to general population by the planet's leading scientists. It appears to be some kind of interactive databank that is supplying them with advanced technology. The scientists cite this as a definitive proof of the benevolent intelligence waiting in the depth of space and urge people to invest into scientific progress to meet them among the stars.

>[Xenophile] We will be waiting
>Interesting
>[Xenophobe] How naive
Bump planet one era ahead, push it to materialism or xenophile. Gain society and influence.

# Object is our: Blank slug

The object we recovered from the [Planet] turned out to be less interesting than we hoped. It's definitely advanced and artificial in origin, but it is also a solid slug made of a supersolid compound. After eliminating all possibilities and not finding and cavities or other hidden compartments, we have to admit that we likely will never get much from it. The design of the slug and material composition had proven to be somewhat useful for our research.

>At least we got something
Gain engineering

# Object is our: Maniac orb

The object that crashed on the surface of [Planet] turned out to be some sort of computer of alien origin encased in a spherical shell. We could not determine anything of its creators, but when we turned it on and established connection to some of our computers and produced a maniacal laughter and announced itself as our overlord, before realizing that it's plugged into a sealed wired network isolated from anything it can use to enslave us. It is now promising us great rewards if we plug it into a bigger network, but our scientists are not inclined to trust it.

>[AI is allowed] Maybe we can figure out some kind of deal?
Progress towards **Maniac orb deal**
>[AI is banned, not spiritualist] Destroy the dangerous machine
Gain 25 influence
>[AI is banned, spiritualist] Destroy the blasphemous machine!
Gain 50 influence and +5% happines empire-wide of ten years
>Disassemble the device and study it
Gain 15% advancement towards the next in chain of combat computers or Adminitstrative AI-self aware logic-Sentient AI chain if there's an opening (chosen randomly). If all are researched, gain a chunk of physics.

# Maniac orb deal: No deal

It seems that negotiations with the alien computer had came to a dead end. Frustrated, one of the scientists assigned to the project had smuggled some construction hardware into the lab and took his frustration out on it with a plasma torch. It is unlikely we would gain any useful intelligence from the puddle on the floor now.

>This was unnecessary
Chain ends

# Maniac orb deal: Agreement made

Today we had struck a bargain with the alien device. In exchange for its cooperation with us we had hooked it up to an endless stream of gossip publications on the data networks from our empire and beyond. Its insights are already helping our military tacticians. 

>Good work
Empire gains "Maniac orb" modifier which increases tracking and evasion of its ships.

# Maniac orb deal: Escape

It seems the device we held in the lab had found a way to trick technicians into shipping it to parts unknown. One of the data terminals contained a note to "filthy peasants" (Presumably us) with promise to not destroy us as we can be instrumental in its plans. We already had found some influence in our systems leeching valuable data and processing power, but it is also providing some military information to our ships. Experts believe that it would not be able to cause lasting harm be its located and removed, but it would take them time to do so.

>We need to stop it
Empire gains "Maniac orb" modifier for about 10 years that increases tracking and evasion of its ships, but also gives -5% to all science. End of the modifier signified by the following event.

# Maniac orb destroyed

Today we had finally traced the alien device that attached itself to our data networks. The security force sent to unplug it was faced with threat of electrocution from local power grid, which encouraged them to use explosives to turn the orb into fine dust.

>Good riddance
Chain ends.

# Object is our: Petulant orb

The device recovered from [Planet] turned out to be an alien computer of a sort, encased in a super-resilient spherical shell. The most notable trait of it is its talkative nature - it is vocalizing by normal means, but also broadcasting on multiple radio frequencies and flashing lights. The message deciphered is always the same - a demand to be returned into space on a loop. Many scientists however can't help but laugh at the device's petulant whining.

>Send it back into space
Progress towards **sending orb into space**
>[AI allowed] Broadcast footage of it live across the empire
Empire gets "Comedy 5gold" modifier for 10 years +10% happiness. 
>[AI is banned, spiritualist] Destroy the blasphemous machine!
Gain 25 influence and +5% happines empire-wide of ten years
>Disassemble the device and study it
Gain 15% advancement towards the next in chain of combat computers or Adminitstrative AI-self aware logic-Sentient AI chain if there's an opening (chosen randomly). If all are researched, gain a chunk of physics.

# Sending orb into space

Spawn engineering "Send orb into space" project

If the orb we got in our hands wants into space so much, we are happy to oblige. Since it doesn't have its own propulsion, we would need to calculate its trajectory more carefully than we had to for a long time.

**On success:** We had commissioned a small civilian freighter to travel to the outskirts of our home system and jettison the orb away at escape velocity. It can now be expected to spend at least a thousand years travelling interstellar space without an incident.

>Its determination is inspiring
Empire gets "Looking in the sky" for 10 years, physics +10%
>[Xenophobe or AI outlawed] Never come back!
Gain 30 influence

# Object is our: Knowledge bank

The object we recovered from [Planet] turned out to be a massive databank encased in a resilient shell. It doesn't contain any information about its origin, however someone put quite a lot of data into it with apparently goal to disseminate knowledge through the galaxy. Some of it is redundant to us and some of it is just plain wrong, but our scientists are already finding gems of knowledge that would take us into a whole new direction.

>[Anyone, xenopbodes included] We could use it
Gain "Knowledge databank" +10% to all science for 10 years
>[Xenophobe] We don't need xeno science
Gain 25 influence and +5% happiness for 10 years

**Comment by ViolentBeetle** [comment]
Event is effectively done, but needs extensive testing.

**Comment by Goldziher** [comment]
I started proof-reading and did about a 1/3 (maybe less). It requires further revision.

**Comment by ViolentBeetle** [comment]
It's in dev now. It was marked is proofread
