### ISSUE TITLE
Science convention fires too often

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#29]
The science convention fires way too often.

Possible solutions (may do more than one):
- Seriously increase the mean time to happen
- Change the event to be a 5 year pulse event
- Only allow it to fire once per game
- Add requirements for it to fire (# of player planets, # of empires contacted)

**Comment by P-aul** [comment]
It shouldn't fire while in war or just after war, especially if you have negative modifiers like "terror bombing", don't know how other nations make the decision now but it should at least partly be based on their ethics/opinion and it should be able to fire for AI (maybe in modified version) where you are "only" invited... generally after having it twice in my games I feel it's a nice idea and with correct basic implementation that feels very underdeveloped however.

**Comment by tzerrell** [comment]
Pull request #30 partially addresses this

**Comment by tzerrell** [comment]
Further addressed by pull request #37 . Not sure if this was intended as long term solution or short term fix, so I'm leaving the issue open.
