### ISSUE TITLE
[Spiritualist Pilgrimage] Check that neighboring country is NOT a FE

### ISSUE THREAD

**Issue by Tuttu** [MoreEventsMod/More_Events_Mod_Beta#319]
Reported by @ViolentBeetle (I guess), I should fix the event so it doesn't trigger with a FE. 
Or when we will rewrite it @Elimdur we might add a special case for FE maybe ?

**Comment by Elimdur** [comment]
That would be very special. Hmm the consequences would either not seem fitting or if we made them fitting they would be over the top. I would just exclude them for good. Just check if the neighbouring empire is a default empire.

**Comment by Elimdur** [comment]
Don´t forget letting the event check for the piligrims country having military access to your space and check for rivalry

**Comment by Tuttu** [comment]
Yep, these changes will be done as well. :)

**Comment by Elimdur** [comment]
Hahaha Tuttu i was too fast.

Fixed it all.

Now only targeting standard empires who are neither your rival nor having rivaled you and who have border access to your space.

Fix is in dev branch.
