### ISSUE TITLE
Hive mind event: Drone 7/9

### ISSUE THREAD

**Issue by Mariawr** [MoreEventsMod/More_Events_Mod_Beta#335]
Most of the writing has been done and the first round of proofreads is through.

(Link removed, I have been doxxed via it)

Balancing is something I'd like to have in the hands of someone who has a bit of experience on game balance, but I'm rather adamant on the rewards being high, given it's a one-time event and players have to pick "unethical" choices to get the best results. If technologies don't work out make it a high amount of society research for studying the drone, and engineering/physics as reward from the swarm.

The drone should have some special trait that makes it a worthwhile leader while at it, but nothing too out of character for a farming and mining drone (maybe industry and biology research bonus?).

The event has been co-authored by my friend "CriticalDawn", who likely won't join as full team member (she doesn't have the game), but has proven pretty helpful at creative input.

**Comment by ViolentBeetle** [comment]
The code for event is alive and well, but someone should read it though and see to it matching the vanilla lore well.

**Comment by ViolentBeetle** [comment]
This is in game
