### ISSUE TITLE
More anomalies for vanilla categories

### ISSUE THREAD

**Issue by Elimdur** [MoreEventsMod/More_Events_Mod_Beta#337]
mountain_uninhabitable_category has only a single anomaly connected to it (giant skeleton)
happens at an inhabitable planet. Anomaly text is:

"Efforts to map the surface of this [Root.GetPlanetMoon] have identified a strange mountain formation in the southern hemisphere. It does not appear to have formed naturally."

Please add some more possible anomalies that may result from that introduction.

**Comment by ViolentBeetle** [comment]
Writing down some ideas for vanilla outcomes, for future implementation

# For mountain formation:
## Feet of Clay
After taking closer look, it became clear that "mountain formation" identified earlier is not a montain formation at all. The crew of [science ship] identified remains several hundred of massive monuments positioned in a row depicting members of unknown species. Most have succumbed to rawaged of time leaving behind only lower extremities, but the technology that allowed someone to erect statues the size of a monuntain are very interesting.
>Planet procudes engineering now

## The writing on the wall
[Science ship] reports that the unusual formation on the surface of [Planet] was indeed neither natural nor mountain. Series of massive rock slabs tower over a valley covered in writings in unknown language.

From a few decyphered fragments it appears the slabs are detailing the entire history of a civilization long gone. However it will take us decades to decypher it all.
>Planet produces society

**Comment by Elimdur** [comment]
With the recent anomaly changes, not needed anymore.
