### ISSUE TITLE
Idea : Partnership with silfae

### ISSUE THREAD

**Issue by Tuttu** [MoreEventsMod/More_Events_Mod_Beta#346]
Here's an idea I'd like to share with you. It consist of two things : a partnership with another modder and a first event idea.

Firstly, I know we decided that we shouldn't have mods dependencies so if you prefer, I will keep this event in a separate mod. However, the idea I have is to create a collection of events available only to people using his portraits and, thus, the custom empire that come with each portraits (Either played by the AI or the player himself). silfae agrees with this idea and will put a link to our mod page when the first event is available (And I think we should put a link to his mod page as well). 

The final plan behind this partnership is that we might _maybe_ ask him to create special portraits for us, like, said, the Orila. I think that would be a good, mutually beneficial agreement. However, I haven't mentionned this with him at the moment as I'm first trying to build a good relation with him before asking something. :)

Now, the first event idea: Glimpse of the past
This idea involves the [Space Raptors](http://steamcommunity.com/sharedfiles/filedetails/?id=872596925). The event is planned to be somewhat rare and available only to people using silfae's raptors' portraits mod. 

This event can start only if you have the AstroRaptors as an neighbour AI empire . They will contact you to explain you they have found an ancient device which offer them a view to another dimension / phase / whatever in which a big meteorite is approaching at quick speed in direction of one of your world. They know for sure that the impact will happen in this dimension as well because they have already been able to see similar mix between the two dimesions happenning on their own planets. They also say that, with your help, they might be able to develop a weapon capable of destroying the meteorite before it would hit your world.

The reality is that the meteorite is going to hit one of their world and they need help to destroy it but they won't ask directly. The final idea for them is even to derout the meteorite to hit one of the players world. So if the player decides to "help" the AstroRaptors, it might not be good for him at all (The chance of the meteorie being derouted instead of destroyed should be really small though).

If you like the whole concept of doing special events involving sylfae's portraits and the idea of this event, I will write the framework for the event and ask a writer to do the writing for me (Because I'm a dick at writing :smile:).

Also, let me quote sylfae on the AstroRaptors so you can get an idea of how they would act in this event: 
> Hm, I understand. Still, given their basic personality, I would imagine that, in that sort of situation, they would still attempt to trick the player rather than ask for help. For example, pretending that they have discovered such a meteorite is really about to crush the player's homeworld, that the player should be so grateful that they've warned him and that they are offering to help him save his planet by starting joint scientific efforts to build this phased-out weapon, while instead they plan to use it to save their own planet.
> 
> Of course; for what concerns the Astroraptors', they were written to be comically full of themselves. While in the particular circumstance of this event they may need help from another Empire, they're still likely to think they are in full control of the situation, and that their prospective ally is just a gullible simpleton. For whoever writes their lines, I'd suggest it's possibly going to be a sort of very condescending, somewhat transparent trickery; the raptor ambassador might not help himself to mock the player for "falling for it" even before the player has provided the necessary help.

**Comment by Elimdur** [comment]
Thinking about special events i did this with one of my starting systems. Hell of a lot of work depending on how complex your events get. You also have to support them once a patch comes and so on.

But you can of course go much more into detail when not having to make an event fit everyone.

So do i assume right, that these events should only work for the prescripted raptor empire?
