### ISSUE TITLE
Diplo event: Space race

### ISSUE THREAD

**Issue by ViolentBeetle** [MoreEventsMod/More_Events_Mod_Beta#356]
Outline for the event.

- Event starts with a random country deciding to host the race. AI might pick or reject the idea based on their ethics/personality (Could just rip off science convention)
- Anyone who accepted the event gets to participate. Obviously, isolationists and purifiers won't ever accept the event
- Looped 14-28 days (Gonna need to balance) event eliminates a country after country. Random list decided what sublight engine tech it's going to be eliminating with weighting towards the weakest. Eliminates one country that has it as a top tech. Only eliminated country receives notification.
- Once we are down to the final 3, they receive special events where their teams are awarded iridium, Rhodium and Osmium medals
- Final event fires that concludes the event notifying everyone who won
- Additionally, if winner is the ai, it would contact player with diplo event to either gloat or congratulate on good game, depending on relationship
- Additionally, MTTH events can fire that would get teams disqualified, such as sabotage, unsportsmanlike behaviour etc
- If any player gets into war, they withdraw
- If host gets into war, the whole event is cancelled

**Comment by Tuttu** [comment]
I had a space race idea based on the Stargate episode where they, well, participate in a space race. Maybe we could mix the two ideas.

**Comment by ViolentBeetle** [comment]
Awaiting proofreading and we'll be done.

**Comment by ViolentBeetle** [comment]
In dev now
