### ISSUE TITLE
Pilgrimage Issue

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#36]
pilgrimage : restrict planet choice --> No homeworld + one-time spawn per playthrought

I'm not quite sure what this means, so just copying Malthus' report of the bug.

**Comment by Tuttu** [comment]
Don't worry about it. I didn't reported it because I will make the fix myself. :)

**Comment by tzerrell** [comment]
This was fixed by pull request #40
