### ISSUE TITLE
Primitives events

### ISSUE THREAD

**Issue by ViolentBeetle** [MoreEventsMod/More_Events_Mod_Beta#360]
Brief list of simple flavor ideas for primitive civilizations. Trigger the observation post

- [X] Moon landing
- [ ] Solar flares fry industrial civilization
- [x] World War, followed by World War II
- [x] Global Pandemic
- [ ] Conspiracy theorist talk show exposes alien activity interfering with wildlife's reproductive cycle
- [x] Major terrorist attack
- [x] Nuclear terrorism/bioterrorism
- [ ] Climate change and famine
- [x] Foundation of a major religion (Christianity, Islam, Buddhism or Scientology)
- [x] Collapse of a major nation (Antique and modern flavour)
- [x] Y2K
- [ ] Cargo cult (suggested by Malthus, if I could come up with a good story that isn't just rehash of Agressive observation fluff from vanilla)

**Comment by Elimdur** [comment]
First FTL prototype flight similar to star trek first contact

in a cold war state civ their spy planes spot some of your observation flights and first mistake them for prototype tech of the opposing superpower. Later as they realise that those where not from their own world they unite with their former foes to form a unified defense against the extraterrestrial threat. (for xenophobe primitive civs) based on this: https://www.youtube.com/watch?v=iQxzWpy7PKg

**Comment by CaligulaCaesar** [comment]
I want to write a "Fall of Rome" event

**Comment by ViolentBeetle** [comment]
Sure, it's still vacant at the moment.

**Comment by CaligulaCaesar** [comment]
The [species] civilisation has been dominated by a single large empire for almost a millennia. With a territory spanning over a fifth of the world's inhabitable surface and containing almost a third of all [specieses] at its height, it has been a hub for learning and culture. Cities have been built, technologies discovered, new levels of prosperity reached. However, over the past fifty years, it seems that the empire has weakened. A combination of internal strife and newly-ascendant external enemies seeking a part of their wealth have laid the empire low. Recently, a large force of what the [speciesan] intelligentsia consider "barbarians" penetrated into the heart of the empire and sacked the capital city before rampaging across the imperial heartlands, looting without restraint.

Although the barbarians later retreated, we do not believe the empire will survive for long. This could set the [speciesans] back considerably.

(Pop dies, building destroyed, goes back an age)
