### ISSUE TITLE
Idea: Fallen Worlds

### ISSUE THREAD

**Issue by ViolentBeetle** [MoreEventsMod/More_Events_Mod_Beta#469]
System cluster: 3-4 habitable systems clustered around L-gate knock-off.

Planets are abandoned planets for the empire. Each has unique role and modifiers:
- Capital
- Agricultural planet
- Industrial world
More pending

If you colonize worlds, you receive a series of events, detailing their rise and fall. Need ideas here: Implications of rebellion and weapon of mass destruction, probably biological.

Once you counted all the way up (You can't decline it, except for not settling the planets), the gate will activate. Original owners of the systems will come knocking. They will request you to give them planets. Your options:
- Ask them to compensate you. Receive ships, technologies and/or resources. 
- Ask them to become your vassal or tributary. They will agree and give positive opinion of you
- If you are in federation, ask them to join your federation. Their opinion will be very high
- Refuse. [Naturally the only option for genocidal empires]
If you refuse, they instantly declare war on you and gain level 10 claims on all the systems. 

They themselves spawn on a system with a single mundane but large planet, protected by tons of void dwellings. 

If given ownership of the systems, they create some pops of their own, and instantly gain control of all unclaimed system as well. 

Once they sorted this part out, they will attempt to buy systems from other countries, if there's any. If vassalized by agreement, they will request being given control of any of their systems, if you conquer them from third party.

Portrait used: Weird eyeless humanoids from DLC, or space elves if weird eyeless humanoids are taken or host doesn't have DLC.

**Comment by ZloyS** [comment]
It is very intersting idea and I would suggest adding some more:

0. I think that every planet should have 'Plague Research Station' as a building (It exists in infection event chain)

1 .I think prison-military planet is an interesting idea. It should contain clone vat, military academy, 2-3 strongholds, and maybe some kind of mining zones etc.
And you can add a background story for it, like "It seems that this planet was a giant prison, where enemies of the regime, criminals and prisoner of war of the long-gone empire were kept for decades. The strongest and the most intelligent of them were under a direct control by 
neuroimplants and served as soldiers/scientists. But, according to planetary administration logs, approximately *number* years ago a huge rebellion, sweeping the whole empire, occured. They couldn't destroy the resistance as it was spreading throughout their home systems, so thew were forced to use their only ace in the hole - newly invented biological weapon.
Something went wrong and this virus started to wipe out the population of all the world. We have to find out what happened next"

After colonising the planet: settlers may find an ancient data bank, containing much more information about the rebellion. For instance, it can say, that "Scientist *Random_Name* found a way to disable neuroimplant. In a small period of time nearly all prisoners were mentally free and started to prepare for uprising. Several months later, it started and insurgents seized several arsenal and a huge spaceport. Then the recording ends with no reason
Also if the Plague Research Station wasn't destroyed and a pop stays on it's tile, an event about disease's features might occur.

2. Some kind of bio-weapon test site as a moon of the Planet above. It Should be a tropical world with 1-2 biolaboratories, 2-3 tile blockers of 'Dangerous Wildlife'. Also, maybe add primitive bronze-age empire?
And a possible story for it: "Apparently, this moon was used as a bio-weapon laboratory and test site. Scientists from *Planet_Name above* invented there a virus, that collapsed the Empire. According to scientific and surveillance camera logs, after when the uprising began to spread in alarming proportions, all tanks with virus, cleared memories of scientists and closed the facility, taking everything valuable with them. Having nothing advanced to use, scientists ran wild and rolled down to Bronze Age

After that you may have events, related to such primitives: for example, they might found a forgotten automatic research assistant, that will give them knowledge and they'll move 1-2 eras forward.
If you have an agressive observation type of observation post, you may get an event of finding untouched cryochamber with deadly toxin, that you can study with different outcomes

3. Cultural-financial center. This 25-tiled Gaia world may have Paradise Dome, Visitor's Centre and some other buildings, related to normal, thriving world
And a story: "Long time ago this planet was a metropolitan planet. A lot of people throughout the System used to come here for acquring cultural and historical knowledge. Local archives, if survived, will definitely say what's happened here"

4. Boundary world. It should be a small planet in the same system as L-Gate. This planet was a point of dispatch for the remaining survivors, that went through L-Gate. One ark didn't manage to launch from the planet and we can examine it's black box. According to it, the rest of rebel attacked this planet, when the evacuation just started. They have already been infected, so won't have any chance to survive. This ark lost his engines, many others left the Known Space through the L-Gate, that they closed behind themselves.
Maybe, this system should have some wrecks of ships and space stations? And 1-2 marked ones such as "Damaged Ship" turning to be another ark and "Disabled Space Station" turning to be a badly damaged L-Gate activation station or some sort of quarantine center with logs about the infected and the panic among refugees

Here you might get events about the last battle between insurgents and the imperial forces, or even a survived ship with only one undamaged cryopod. After opening it you will face a former Minister of Internal Security/Minister of Health/Stronghold Governor, that can say their own vision of the conflict. After that you can take him/her into your leader pool.

Also, possible modifiers (planetary) for planets are:
・Prison planet - "Abandoned Neuro-implantation Stations" providing +15% to social output, +15% to government ethics attraction and -10% to happiness
・Bio-weapon test site planet - "Bio-weapon range" providing +30% to social output, -10% to happiness and -15% to habitability
・Cultural-financial center - "Ancient Metropolitan World" providing +10% to migration popularity, +10% to unity and +10% to research output
・Boundary world - "Ancient battle remnants" providing +15% to engineering output, -10% to happiness and -10% to building cost

**Comment by ViolentBeetle** [comment]
While it has failed to my initial ambition, it is now in dev as mem_sadrell chain
