### ISSUE TITLE
Spiritualist Pilgrimage not happening

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#48]
The spiritualist pilgrimage event does not seem to be happening even after a long time with all conditions met (up to year 70-ish with two humans and several spiritualist AIs).

**Comment by Tuttu** [comment]
Can you confirm that this issue still exists with the latest version of the code (Which you weren't using) ?

**Comment by tzerrell** [comment]
This is going to require a long-term test, so that's best addressed in one of our multiplayer tests. But since the worst that can happen is the event doesn't spawn, I think we can just leave the code in and know to be on the lookout for this next long test.
