### ISSUE TITLE
Demon Ship event 1 needs more testing

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#51]
I made a minor balance change to the demon ship event 1.a reward. It's small enough I'm moving it straight in to `stable`, but we should have a second person test it since I'm putting it in `stable`

**Comment by tzerrell** [comment]
"add_anomaly mem_demonship_category" in console to test (then survey and follow the event/project to one of its conclusions)

**Comment by Tuttu** [comment]
I started the anomaly multiple times and I think I tried all the possible outcome. 
There are multiple instance of **ftl** written in lowercase so I would suggest to take a pass on all your text to change the **ftl** to **FTL**. :)
Also, the text for "FTL-prototype destroyed" (When you chose to destroy it by yourself) is completely missing. Is that intended ?

Apart from that, I face no errors.

**Comment by tzerrell** [comment]
ftl -> FTL fixed and other bug did not reproduce on other machines.
