### ISSUE TITLE
Broken Clock ring world not compatible with 2.3

### ISSUE THREAD

**Issue by dcelasun** [MoreEventsMod/More_Events_Mod_Beta#525]
In Stellaris 2.3 ring world segments have 5 districts, but each district provides a ton of housing and jobs. Previously the number of districts was 50, which caused massive empire sprawl to the point of making ring worlds unusable.

Unfortunately, the ring world spawned with the Broken Clock event chain still has 50 of the version 2.2 districts:

![image](https://user-images.githubusercontent.com/144373/60686583-9e0baf80-9ea1-11e9-9980-92314858e390.png)

This basically makes the system unusable.

**Comment by ViolentBeetle** [comment]
It's been fixed long ago internally, size adjusted, closing for now.
