### ISSUE TITLE
Idea: Dread Pirate Mask

### ISSUE THREAD

**Issue by ViolentBeetle** [MoreEventsMod/More_Events_Mod_Beta#526]
The general outline for a story involving a relic - a scary looking mask (Final design pending)
![scary_mask_tiny](https://user-images.githubusercontent.com/25012226/61403799-c1415080-a8de-11e9-813d-6fe3c1497972.png)

The supposed storyline:

- Finding a dig site. Random roll or perhaps use an anomaly, like rubricator. The latter is better as it would limit AI from gaining it needlessly. 
- Dig site needs to be long a detailed. Some cool story bits.
- A war torn planet where the Dread Pirate made his last stand
- Bridge somehow to encountering the pirate galleon with top-tier weaponry.
- This pirate galleon was merely a pretender. Encounter the real dread pirate - flying oversized Cybrex ship perhaps (Mass Effect I references possible)

**Comment by ViolentBeetle** [comment]
**Considered idea for initial dig: Fatal Attraction**
- Find a ship looking for mask
- Uncover dig site called "Fatal Attraction", follow multiple expeditions and their fight for the mask, as well as danger of ruins.

**Comment by whitewolf87** [comment]
So for one stage, here's a possibility:

Remnants of a Ground Battle

- Obvious that the Dread Pirate set up a bastion of some sort
- Was at the battle site for a very long time, maybe even through several civilization cycles
- Is not here anymore
- Layers of remnants of various species and their buried small arms trying to engage the pirate at some point or another by charging the bastion. Remains layered with the most recent attempt at a charge on top
- Minor treasure inside bastion

**Comment by ViolentBeetle** [comment]
3 locations I currently settled on:
- Lobby/hangar where different groups started the dig. After a while they turned on each other.
- Caved-in section. PDA from a researcher who was fired for warning about cave-in danger because he "Didn't believe in the mission"
- Final chamber, from which something escaped making now caved-in tunnel to the side. The last surviving researcher found it already empty and didn't have supplies to make it to the surface, so he died there.

Need 3 more.

**Comment by ViolentBeetle** [comment]
It's in the game now
