### ISSUE TITLE
Star Survey deposit clearing

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#67]
There are potential issues with the star survey project that sets a deposit on the star as a reward (I believe this is the bright star).
- In multiplayer, will it clear a deposit someone else has seen?
- In multiplayer, will multiple people be assigned the same star?

Possible solution: flag each star that has been used for the event and only let the event target unflagged stars. Concern: what if more players get the event than there are stars?

**Comment by tzerrell** [comment]
For the class A stars, you can check for no deposit with `orbital_deposit_tile = { has_deposit = d_null_deposit }`; however `has_deposit = no` will not work. This doesn't solve all of these problems but it helps some.

**Comment by P-aul** [comment]
After the changed proposed above it would be good to see how this behaves in specific conditions - multiplayer game with very small galaxy so two players get it on the same star. There is also a chance that, in very small galaxies, no suitable star can be found. Other proposed solution is to change the reward.

**Comment by P-aul** [comment]
Pull request #83 is a fix for that problem, changing the rewards in that event. Needs some testing and new translation

**Comment by tzerrell** [comment]
I've tested this and it seems fine. I believe all that's outstanding is the translation, so I'm removing the other tags, but feel free to put them back on if I'm mistaken

**Comment by tzerrell** [comment]
The Spanish text that we still need has been temporarily replaced with English; that issue is now listed as #147 .
