### ISSUE TITLE
Recruitement : artist for the mod

### ISSUE THREAD

**Issue by Tuttu** [MoreEventsMod/More_Events_Mod_Beta#71]
We discuss about it already, it might be really good for the mod to have a dedicated artist willing to provide arts for us like new buildings, techs or icons. 
It could help us add even more added value to the mod. :)

**Comment by Dracia** [comment]
I can shop stuff extensively but drawing is out of my league. But if you are content with shopping-ask away!

**Comment by tzerrell** [comment]
While it wouldn't hurt to have more artists, we now have enough that it's no longer a critical need (at least in my opinion). So I'm closing this.
