### ISSUE TITLE
Enterprise of the Fallen (Pending name)

### ISSUE THREAD

**Issue by Tuttu** [MoreEventsMod/More_Events_Mod_Beta#73]
Adding a new event based on an idea by Talanic (PDX forum) where you discover ruins from an ancient civ that seemed technologically advanced. Truth is they were just dreaming of being that advanced and they wrote many story about this.
Current version (Dev branch) is working but really simple. I have expanded it and I'm hunting bugs at the moment. :)

**Comment by tzerrell** [comment]
This is cool! I'll mention that the feature branch for this is `enterprise-fallen` and to test it you can use `add_anomaly ef_temp_category` with a planet selected (at least at the moment).

**Comment by Tuttu** [comment]
Yep, good additions. :)

**Comment by Tuttu** [comment]
The anomaly is now complete and ready for testing. It should spawn on its own on tomb worlds but you can spawn it by following @tcarrell instruction above.
Note that to test all the possible outcomes, you need to have either a **Xenophile** or **Xenophobe** ethic (Fanatic variations included for both). 
NOTE : You also have to wait 5 years (+/- 1,5 years) after you have discovered the library to get the rest of the event chain.

**Comment by tzerrell** [comment]
- The planet name is not appearing correctly in the anomaly category description.
- I do not see anything special for xenophiles or xenophobes

**Comment by Tuttu** [comment]
What do you mean by not appearing correctly ? It's not colored or it doesn't appear at all ?

As for the Xenophile / Xenophobe thing, you have to wait 5 years (+/- 1,5 years) after you have discovered the library to get the rest of the event chain. :) 
I will edit my first message to include this point.

**Comment by tzerrell** [comment]
Planet name: Nothing is appearing at all.

And thanks for the heads up on the xenoph\* thing, I definitely had not tested long enough

**Comment by Tuttu** [comment]
No problem, it was my fault. I will check what's wrong with the planet name.

**Comment by Tuttu** [comment]
Name problem should be fixed now. I was unable to merge the pull request myself though.

**Comment by tzerrell** [comment]
The fix to the name problem looks good, and I've gotten the xenophile version of the event now and it seems fine. I'm closing this issue as I think this is sufficiently tested.
