### ISSUE TITLE
Ancient Robots: Fix references in loc files

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#75]
The english localisation file for the Ancient Robots event does not have appropriate references; instead it contains summary explanations like [planet_name] and [scientist_name]. These need to be set up with the correct references.

**Comment by tzerrell** [comment]
I'm assigning this issue to @Tuttu since it's a part of #79 which he's working on.

**Comment by Tuttu** [comment]
No problem. :)

**Comment by Elimdur** [comment]
Planet name is not shown in the first event text

**Comment by tzerrell** [comment]
This seems like it is likely resolved so I'm closing it, but reopen if it's still an issue.
