### ISSUE TITLE
Science Convention: Fires with no aliens

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#76]
We may want to redesign the science convention so that it only fires if you are in contact with aliens. We may also consider requiring a minimum number of alien contacts and even a minimum number of planets in your own empire.

This will be an easy change to make and I'm happy to do so, but I wanted to leave an issue open for this for a couple of days to see if there were any comments rather than make a unilateral change.

**Comment by Tuttu** [comment]
Good set of changes. It will improve the event a lot. :)

**Comment by tzerrell** [comment]
committed for the 1.3.1 beta release; tried to let the AI use this event too but it didn't work well so I removed that. This is commit 4b6e75c
