### ISSUE TITLE
Science convention never started by aliens

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#77]
Perhaps we could let a science convention fire for aliens -- just let them only accept it with a very low probability (1/20th of the chance for a player?)

**Comment by Tuttu** [comment]
I agree this should be a thing. It could be really cool to be invited from time to time. :)

**Comment by tzerrell** [comment]
I'm closing this as a successful test of the proposed fix to #171 will also fix this.
