### ISSUE TITLE
Finish Coding Ancient Robots

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#79]
The ancient robots event is about two thirds done and needs a coder to take over. Asnys left some notes in Notes.txt in the root directory for whoever continues the coding. The branch is `ancient-robots`.

See also #75 for a known bug.

**Comment by tzerrell** [comment]
@Tuttu I know you said you might be interested, if so, assign this to yourself so the rest of the team knows.

**Comment by Tuttu** [comment]
I won't assign it to me yet. Maybe someone would like to work on it instead. :)

**Comment by ghost** [comment]
I'm on it.

**Comment by ghost** [comment]
Code prototype is completed.  On to testing, for which I'm opening a separate issue.
