### ISSUE TITLE
Test Poisoned World Anomalies

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#80]
A pair of poisoned world anomalies are ready for testing. With the branch `dev` or `poisoned-world` loaded, run `add_anomaly mem_poisoned_world_category` with a planet selected, then survey it. There are two possible success anomalies and one possible failure event, and all need to be tested.

**Comment by Tuttu** [comment]
You might want to color you variable name like this: `§Y[From.GetName]§!`
Also the failure put my science ship to 96,6% HP. You might want to increase the damage a bit (Around 80% HP left maybe) to give it more impact I think.

Apart from that, I encountered no problem. :)

Edit: One more thing. You might want to use "Science Officer" [name] when referring to it as they do in vanilla.

**Comment by tzerrell** [comment]
Good catch on the science officer. I'll look into getting the yellow text in as well.

The very minor damage is intentional, so I'm going to leave it as-is.

**Comment by tzerrell** [comment]
science officer fixed; coloring left unchanged pending a decision on how we're doing colors in our mod
