### ISSUE TITLE
Test Mysterious Pyramids Anomalies

### ISSUE THREAD

**Issue by tzerrell** [MoreEventsMod/More_Events_Mod_Beta#84]
A pair of mysterious pyramid anomalies are ready for testing. With the branch `dev` or `mysterious-pyramids` loaded, run `add_anomaly mem_mysterious_pyramids_category` with a planet selected, then survey it. There are two possible success anomalies and one possible failure event, and all need to be tested.

**Comment by Tuttu** [comment]
Nothing to say apart this : 
You might want to color you variable name like this: §Y[From.GetName]§!
One more thing. You might want to use "Science Officer" [name] when referring to it as they do in vanilla.

No problem this time again. :)

**Comment by tzerrell** [comment]
Science Officers now given the respect they deserve ;)

Variable colors not changed pending a decision on what our variable coloring standard for the mod will be.
