### ISSUE TITLE
[Foreign Musicians] A given empire shouldn't send you musician more than one time

### ISSUE THREAD

**Issue by Tuttu** [MoreEventsMod/More_Events_Mod_Beta#96]
http://forum.paradoxplaza.com/forum/index.php?threads/mod-more-events-mod-new-beta-available.945016/page-3#post-21528150

Good point from Mitchz95 who has been really unlucky. When Foreign Musicians come from an empire, we should use a flag to prevent this empire from sending musician more than one time.

**Comment by Elimdur** [comment]
if it is not possible to make a limit per empire it should be limited to a one time event per player.

And if it is possible to let it happen multiple times each time from a different empire then the chance for it to happen should be lower. If he had it 3 times in a single game this sounds too much for me atleast.

**Comment by Tuttu** [comment]
It's possible with country flags, don't worry. :)

**Comment by tzerrell** [comment]
Fixed by a09ec50b

**Comment by tzerrell** [comment]
The earlier fix was incomplete -- commit cf6ece8 is also needed to complete fix.
