### ISSUE TITLE
[Science Con] Core planet cap no longer exists

### ISSUE THREAD

**Issue by Zednosius** [MoreEventsMod/More_Events_Mod_Beta#99]
With 1.2 they changed the core planet count to core systems. As a result the improvement tech is now
tech_repeatable_improved_core_system_cap
instead of
tech_repeatable_improved_core_planet_cap
. 
planet cap is still used in the code so it currently throws an error.

**Comment by tzerrell** [comment]
I think this is coming from science convention critical success events. I'll look into it.
